/* defaults.c generated by valac, the Vala compiler
 * generated from defaults.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>




#define DEFAULT_WIDTH 800
#define DEFAULT_HEIGHT 480
#define ICON_SIZE GTK_ICON_SIZE_DND
#define DEFAULT_STYLE "\nstyle \"custom\"\n{\n    GtkRange::slider-width = 12\n    GtkComboBox::arrow-size = 12\n    GtkComboBox::appears-as-list = 1\n    font_name = \"Sans 12\"\n}\n\nwidget_class \"*\" style \"custom\"\n"





