/* error-dialog.c generated by valac, the Vala compiler
 * generated from error-dialog.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>


#define TYPE_ERROR_DIALOG (error_dialog_get_type ())
#define ERROR_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ERROR_DIALOG, ErrorDialog))
#define ERROR_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ERROR_DIALOG, ErrorDialogClass))
#define IS_ERROR_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ERROR_DIALOG))
#define IS_ERROR_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ERROR_DIALOG))
#define ERROR_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ERROR_DIALOG, ErrorDialogClass))

typedef struct _ErrorDialog ErrorDialog;
typedef struct _ErrorDialogClass ErrorDialogClass;
typedef struct _ErrorDialogPrivate ErrorDialogPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ErrorDialog {
	GtkWindow parent_instance;
	ErrorDialogPrivate * priv;
	GtkTextBuffer* text_buffer;
};

struct _ErrorDialogClass {
	GtkWindowClass parent_class;
};


static gpointer error_dialog_parent_class = NULL;

GType error_dialog_get_type (void);
enum  {
	ERROR_DIALOG_DUMMY_PROPERTY
};
void error_dialog_text_insert_new_line (ErrorDialog* self, GtkTextIter* iter);
void error_dialog_add_error_with_debug (ErrorDialog* self, GError* _error_, const char* debug);
GtkButton* new_button_with_stock_image (const char* stock_id);
static void _lambda1_ (ErrorDialog* self);
static void __lambda1__gtk_button_clicked (GtkButton* _sender, gpointer self);
GtkBox* error_dialog_new_error_box (ErrorDialog* self);
ErrorDialog* error_dialog_new (void);
ErrorDialog* error_dialog_construct (GType object_type);
static GObject * error_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void error_dialog_finalize (GObject* obj);



void error_dialog_add_error_with_debug (ErrorDialog* self, GError* _error_, const char* debug) {
	GtkTextIter iter = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (debug != NULL);
	gtk_text_buffer_get_end_iter (self->text_buffer, &iter);
	error_dialog_text_insert_new_line (self, &iter);
	gtk_text_buffer_insert_with_tags_by_name (self->text_buffer, &iter, _error_->message, -1, "bold", NULL, NULL);
	error_dialog_text_insert_new_line (self, &iter);
	gtk_text_buffer_insert (self->text_buffer, &iter, debug, -1);
	error_dialog_text_insert_new_line (self, &iter);
}


void error_dialog_text_insert_new_line (ErrorDialog* self, GtkTextIter* iter) {
	g_return_if_fail (self != NULL);
	gtk_text_buffer_insert (self->text_buffer, iter, "\n", -1);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _lambda1_ (ErrorDialog* self) {
	g_signal_emit_by_name (self, "closed");
}


static void __lambda1__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	_lambda1_ (self);
}


GtkBox* error_dialog_new_error_box (ErrorDialog* self) {
	GtkBox* result;
	GtkVBox* box;
	GtkScrolledWindow* scrolled_window;
	GtkTextView* text_view;
	GtkTextBuffer* _tmp0_;
	GtkHButtonBox* button_box;
	GtkButton* close_button;
	g_return_val_if_fail (self != NULL, NULL);
	box = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 6));
	scrolled_window = g_object_ref_sink ((GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL));
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) scrolled_window, TRUE, TRUE, (guint) 0);
	gtk_scrolled_window_set_policy (scrolled_window, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	text_view = g_object_ref_sink ((GtkTextView*) gtk_text_view_new ());
	gtk_text_view_set_editable (text_view, FALSE);
	gtk_text_view_set_cursor_visible (text_view, FALSE);
	gtk_text_view_set_wrap_mode (text_view, GTK_WRAP_WORD);
	self->text_buffer = (_tmp0_ = _g_object_ref0 (gtk_text_view_get_buffer (text_view)), _g_object_unref0 (self->text_buffer), _tmp0_);
	gtk_container_add ((GtkContainer*) scrolled_window, (GtkWidget*) text_view);
	button_box = g_object_ref_sink ((GtkHButtonBox*) gtk_hbutton_box_new ());
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) button_box, FALSE, FALSE, (guint) 6);
	gtk_button_box_set_layout ((GtkButtonBox*) button_box, GTK_BUTTONBOX_END);
	close_button = new_button_with_stock_image (GTK_STOCK_CLOSE);
	gtk_container_add ((GtkContainer*) button_box, (GtkWidget*) close_button);
	g_signal_connect_object (close_button, "clicked", (GCallback) __lambda1__gtk_button_clicked, self, 0);
	gtk_widget_show_all ((GtkWidget*) box);
	result = (GtkBox*) box;
	_g_object_unref0 (scrolled_window);
	_g_object_unref0 (text_view);
	_g_object_unref0 (button_box);
	_g_object_unref0 (close_button);
	return result;
}


ErrorDialog* error_dialog_construct (GType object_type) {
	ErrorDialog * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


ErrorDialog* error_dialog_new (void) {
	return error_dialog_construct (TYPE_ERROR_DIALOG);
}


static GObject * error_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ErrorDialog * self;
	parent_class = G_OBJECT_CLASS (error_dialog_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = ERROR_DIALOG (obj);
	{
		GtkBox* box;
		gtk_window_set_title ((GtkWindow*) self, "Error");
		box = error_dialog_new_error_box (self);
		gtk_container_add ((GtkContainer*) self, (GtkWidget*) box);
		gtk_text_buffer_create_tag (self->text_buffer, "bold", "weight", PANGO_WEIGHT_BOLD, NULL, NULL);
		_g_object_unref0 (box);
	}
	return obj;
}


static void error_dialog_class_init (ErrorDialogClass * klass) {
	error_dialog_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = error_dialog_constructor;
	G_OBJECT_CLASS (klass)->finalize = error_dialog_finalize;
	g_signal_new ("closed", TYPE_ERROR_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void error_dialog_instance_init (ErrorDialog * self) {
}


static void error_dialog_finalize (GObject* obj) {
	ErrorDialog * self;
	self = ERROR_DIALOG (obj);
	_g_object_unref0 (self->text_buffer);
	G_OBJECT_CLASS (error_dialog_parent_class)->finalize (obj);
}


GType error_dialog_get_type (void) {
	static GType error_dialog_type_id = 0;
	if (error_dialog_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (ErrorDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) error_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ErrorDialog), 0, (GInstanceInitFunc) error_dialog_instance_init, NULL };
		error_dialog_type_id = g_type_register_static (GTK_TYPE_WINDOW, "ErrorDialog", &g_define_type_info, 0);
	}
	return error_dialog_type_id;
}




