/* error-dialog.c generated by valac, the Vala compiler
 * generated from error-dialog.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>


#define OMAP_TYPE_DEBUG_DIALOG (omap_debug_dialog_get_type ())
#define OMAP_DEBUG_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMAP_TYPE_DEBUG_DIALOG, OmapDebugDialog))
#define OMAP_DEBUG_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMAP_TYPE_DEBUG_DIALOG, OmapDebugDialogClass))
#define OMAP_IS_DEBUG_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMAP_TYPE_DEBUG_DIALOG))
#define OMAP_IS_DEBUG_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMAP_TYPE_DEBUG_DIALOG))
#define OMAP_DEBUG_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMAP_TYPE_DEBUG_DIALOG, OmapDebugDialogClass))

typedef struct _OmapDebugDialog OmapDebugDialog;
typedef struct _OmapDebugDialogClass OmapDebugDialogClass;
typedef struct _OmapDebugDialogPrivate OmapDebugDialogPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define OMAP_TYPE_ERROR_DIALOG (omap_error_dialog_get_type ())
#define OMAP_ERROR_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMAP_TYPE_ERROR_DIALOG, OmapErrorDialog))
#define OMAP_ERROR_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMAP_TYPE_ERROR_DIALOG, OmapErrorDialogClass))
#define OMAP_IS_ERROR_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMAP_TYPE_ERROR_DIALOG))
#define OMAP_IS_ERROR_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMAP_TYPE_ERROR_DIALOG))
#define OMAP_ERROR_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMAP_TYPE_ERROR_DIALOG, OmapErrorDialogClass))

typedef struct _OmapErrorDialog OmapErrorDialog;
typedef struct _OmapErrorDialogClass OmapErrorDialogClass;
typedef struct _OmapErrorDialogPrivate OmapErrorDialogPrivate;

struct _OmapDebugDialog {
	GtkDialog parent_instance;
	OmapDebugDialogPrivate * priv;
	GtkTextBuffer* text_buffer;
	gint errors_n;
};

struct _OmapDebugDialogClass {
	GtkDialogClass parent_class;
};

struct _OmapErrorDialog {
	GtkMessageDialog parent_instance;
	OmapErrorDialogPrivate * priv;
};

struct _OmapErrorDialogClass {
	GtkMessageDialogClass parent_class;
};


static gpointer omap_debug_dialog_parent_class = NULL;
static gpointer omap_error_dialog_parent_class = NULL;

GType omap_debug_dialog_get_type (void) G_GNUC_CONST;
enum  {
	OMAP_DEBUG_DIALOG_DUMMY_PROPERTY
};
OmapDebugDialog* omap_debug_dialog_new (GtkWindow* parent);
OmapDebugDialog* omap_debug_dialog_construct (GType object_type, GtkWindow* parent);
void omap_debug_dialog_on_destroy (OmapDebugDialog* self);
void omap_debug_dialog_on_response (OmapDebugDialog* self);
void omap_debug_dialog_text_insert_new_line (OmapDebugDialog* self, GtkTextIter* iter);
void omap_debug_dialog_add_error_debug (OmapDebugDialog* self, GError* _error_, const char* debug);
GtkBox* omap_debug_dialog_new_error_box (OmapDebugDialog* self);
static void _omap_debug_dialog_on_destroy_gtk_object_destroy (GtkObject* _sender, gpointer self);
static void _omap_debug_dialog_on_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static GObject * omap_debug_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void omap_debug_dialog_finalize (GObject* obj);
GType omap_error_dialog_get_type (void) G_GNUC_CONST;
enum  {
	OMAP_ERROR_DIALOG_DUMMY_PROPERTY
};
OmapErrorDialog* omap_error_dialog_new (GError* e);
OmapErrorDialog* omap_error_dialog_construct (GType object_type, GError* e);
void omap_error_dialog_on_response (OmapErrorDialog* self);
static void _omap_error_dialog_on_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static GObject * omap_error_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
GtkMessageDialog* omap_error_dialog (GError* e);



OmapDebugDialog* omap_debug_dialog_construct (GType object_type, GtkWindow* parent) {
	OmapDebugDialog * self;
	gint width = 0;
	gint height = 0;
	g_return_val_if_fail (parent != NULL, NULL);
	self = g_object_newv (object_type, 0, NULL);
	gtk_window_get_size (parent, &width, &height);
	gtk_window_set_default_size ((GtkWindow*) self, (3 * width) / 4, (3 * height) / 4);
	gtk_window_set_transient_for ((GtkWindow*) self, parent);
	return self;
}


OmapDebugDialog* omap_debug_dialog_new (GtkWindow* parent) {
	return omap_debug_dialog_construct (OMAP_TYPE_DEBUG_DIALOG, parent);
}


void omap_debug_dialog_on_destroy (OmapDebugDialog* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "closed");
}


void omap_debug_dialog_on_response (OmapDebugDialog* self) {
	g_return_if_fail (self != NULL);
	gtk_object_destroy ((GtkObject*) self);
}


void omap_debug_dialog_add_error_debug (OmapDebugDialog* self, GError* _error_, const char* debug) {
	GtkTextIter iter = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (debug != NULL);
	self->errors_n++;
	if (self->errors_n > 1) {
		char* _tmp0_;
		gtk_window_set_title ((GtkWindow*) self, _tmp0_ = g_strdup_printf ("%d errors", self->errors_n));
		_g_free0 (_tmp0_);
	}
	gtk_text_buffer_get_end_iter (self->text_buffer, &iter);
	omap_debug_dialog_text_insert_new_line (self, &iter);
	gtk_text_buffer_insert_with_tags_by_name (self->text_buffer, &iter, _error_->message, -1, "bold", NULL, NULL);
	omap_debug_dialog_text_insert_new_line (self, &iter);
	if (debug != NULL) {
		gtk_text_buffer_insert (self->text_buffer, &iter, debug, -1);
		omap_debug_dialog_text_insert_new_line (self, &iter);
	}
}


void omap_debug_dialog_text_insert_new_line (OmapDebugDialog* self, GtkTextIter* iter) {
	g_return_if_fail (self != NULL);
	gtk_text_buffer_insert (self->text_buffer, iter, "\n", -1);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GtkBox* omap_debug_dialog_new_error_box (OmapDebugDialog* self) {
	GtkBox* result = NULL;
	GtkHBox* box;
	GtkImage* image;
	GtkVSeparator* separator;
	GtkScrolledWindow* scrolled_window;
	GtkPolicyType policy;
	GtkTextView* text_view;
	GtkTextBuffer* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	box = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 0));
	image = g_object_ref_sink ((GtkImage*) gtk_image_new_from_stock (GTK_STOCK_DIALOG_ERROR, GTK_ICON_SIZE_DIALOG));
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) image, FALSE, FALSE, (guint) 3);
	separator = g_object_ref_sink ((GtkVSeparator*) gtk_vseparator_new ());
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) separator, FALSE, FALSE, (guint) 0);
	scrolled_window = g_object_ref_sink ((GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL));
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) scrolled_window, TRUE, TRUE, (guint) 0);
	policy = GTK_POLICY_AUTOMATIC;
	gtk_scrolled_window_set_policy (scrolled_window, policy, policy);
	text_view = g_object_ref_sink ((GtkTextView*) gtk_text_view_new ());
	gtk_container_add ((GtkContainer*) scrolled_window, (GtkWidget*) text_view);
	gtk_text_view_set_editable (text_view, FALSE);
	gtk_text_view_set_cursor_visible (text_view, FALSE);
	gtk_text_view_set_wrap_mode (text_view, GTK_WRAP_WORD);
	self->text_buffer = (_tmp0_ = _g_object_ref0 (gtk_text_view_get_buffer (text_view)), _g_object_unref0 (self->text_buffer), _tmp0_);
	gtk_widget_show_all ((GtkWidget*) box);
	result = (GtkBox*) box;
	_g_object_unref0 (text_view);
	_g_object_unref0 (scrolled_window);
	_g_object_unref0 (separator);
	_g_object_unref0 (image);
	return result;
}


static void _omap_debug_dialog_on_destroy_gtk_object_destroy (GtkObject* _sender, gpointer self) {
	omap_debug_dialog_on_destroy (self);
}


static void _omap_debug_dialog_on_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	omap_debug_dialog_on_response (self);
}


static GObject * omap_debug_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	OmapDebugDialog * self;
	parent_class = G_OBJECT_CLASS (omap_debug_dialog_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = OMAP_DEBUG_DIALOG (obj);
	{
		GtkWidget* _tmp0_;
		GtkBox* content_area;
		GtkBox* _tmp1_;
		gtk_window_set_title ((GtkWindow*) self, "Error");
		gtk_window_set_modal ((GtkWindow*) self, TRUE);
		gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_CLOSE, (gint) GTK_RESPONSE_CLOSE);
		content_area = _g_object_ref0 ((_tmp0_ = gtk_dialog_get_content_area ((GtkDialog*) self), GTK_IS_BOX (_tmp0_) ? ((GtkBox*) _tmp0_) : NULL));
		gtk_container_add ((GtkContainer*) content_area, (GtkWidget*) (_tmp1_ = omap_debug_dialog_new_error_box (self)));
		_g_object_unref0 (_tmp1_);
		gtk_text_buffer_create_tag (self->text_buffer, "bold", "weight", PANGO_WEIGHT_BOLD, NULL, NULL);
		g_signal_connect_object ((GtkObject*) self, "destroy", (GCallback) _omap_debug_dialog_on_destroy_gtk_object_destroy, self, 0);
		g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) _omap_debug_dialog_on_response_gtk_dialog_response, self, 0);
		_g_object_unref0 (content_area);
	}
	return obj;
}


static void omap_debug_dialog_class_init (OmapDebugDialogClass * klass) {
	omap_debug_dialog_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = omap_debug_dialog_constructor;
	G_OBJECT_CLASS (klass)->finalize = omap_debug_dialog_finalize;
	g_signal_new ("closed", OMAP_TYPE_DEBUG_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void omap_debug_dialog_instance_init (OmapDebugDialog * self) {
}


static void omap_debug_dialog_finalize (GObject* obj) {
	OmapDebugDialog * self;
	self = OMAP_DEBUG_DIALOG (obj);
	_g_object_unref0 (self->text_buffer);
	G_OBJECT_CLASS (omap_debug_dialog_parent_class)->finalize (obj);
}


GType omap_debug_dialog_get_type (void) {
	static volatile gsize omap_debug_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&omap_debug_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (OmapDebugDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) omap_debug_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OmapDebugDialog), 0, (GInstanceInitFunc) omap_debug_dialog_instance_init, NULL };
		GType omap_debug_dialog_type_id;
		omap_debug_dialog_type_id = g_type_register_static (GTK_TYPE_DIALOG, "OmapDebugDialog", &g_define_type_info, 0);
		g_once_init_leave (&omap_debug_dialog_type_id__volatile, omap_debug_dialog_type_id);
	}
	return omap_debug_dialog_type_id__volatile;
}


OmapErrorDialog* omap_error_dialog_construct (GType object_type, GError* e) {
	OmapErrorDialog * self;
	self = g_object_newv (object_type, 0, NULL);
	g_object_set ((GtkMessageDialog*) self, "text", e->message, NULL);
	return self;
}


OmapErrorDialog* omap_error_dialog_new (GError* e) {
	return omap_error_dialog_construct (OMAP_TYPE_ERROR_DIALOG, e);
}


void omap_error_dialog_on_response (OmapErrorDialog* self) {
	g_return_if_fail (self != NULL);
	gtk_object_destroy ((GtkObject*) self);
}


static void _omap_error_dialog_on_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	omap_error_dialog_on_response (self);
}


static GObject * omap_error_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	OmapErrorDialog * self;
	parent_class = G_OBJECT_CLASS (omap_error_dialog_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = OMAP_ERROR_DIALOG (obj);
	{
		g_object_set ((GtkMessageDialog*) self, "message-type", GTK_MESSAGE_ERROR, NULL);
		gtk_window_set_title ((GtkWindow*) self, "Error");
		gtk_window_set_modal ((GtkWindow*) self, TRUE);
		gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_CLOSE, (gint) GTK_RESPONSE_CLOSE);
		g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) _omap_error_dialog_on_response_gtk_dialog_response, self, 0);
	}
	return obj;
}


static void omap_error_dialog_class_init (OmapErrorDialogClass * klass) {
	omap_error_dialog_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = omap_error_dialog_constructor;
}


static void omap_error_dialog_instance_init (OmapErrorDialog * self) {
}


GType omap_error_dialog_get_type (void) {
	static volatile gsize omap_error_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&omap_error_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (OmapErrorDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) omap_error_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OmapErrorDialog), 0, (GInstanceInitFunc) omap_error_dialog_instance_init, NULL };
		GType omap_error_dialog_type_id;
		omap_error_dialog_type_id = g_type_register_static (GTK_TYPE_MESSAGE_DIALOG, "OmapErrorDialog", &g_define_type_info, 0);
		g_once_init_leave (&omap_error_dialog_type_id__volatile, omap_error_dialog_type_id);
	}
	return omap_error_dialog_type_id__volatile;
}


GtkMessageDialog* omap_error_dialog (GError* e) {
	GtkMessageDialog* result = NULL;
	OmapErrorDialog* dialog;
	dialog = g_object_ref_sink (omap_error_dialog_new (e));
	gtk_widget_show ((GtkWidget*) dialog);
	result = (GtkMessageDialog*) dialog;
	return result;
}




