/* media-window.c generated by valac, the Vala compiler
 * generated from media-window.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MEDIA_WINDOW (media_window_get_type ())
#define MEDIA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MEDIA_WINDOW, MediaWindow))
#define MEDIA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MEDIA_WINDOW, MediaWindowClass))
#define IS_MEDIA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MEDIA_WINDOW))
#define IS_MEDIA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MEDIA_WINDOW))
#define MEDIA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MEDIA_WINDOW, MediaWindowClass))

typedef struct _MediaWindow MediaWindow;
typedef struct _MediaWindowClass MediaWindowClass;
typedef struct _MediaWindowPrivate MediaWindowPrivate;

#define MEDIA_WINDOW_TYPE_TAB (media_window_tab_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _gtk_icon_info_free0(var) ((var == NULL) ? NULL : (var = (gtk_icon_info_free (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

struct _MediaWindow {
	GtkWindow parent_instance;
	MediaWindowPrivate * priv;
	GtkNotebook* notebook;
	GtkToolbar* toolbar;
	GtkVBox* main_box;
	gboolean is_fullscreen;
};

struct _MediaWindowClass {
	GtkWindowClass parent_class;
};

typedef enum  {
	MEDIA_WINDOW_TAB_LIST,
	MEDIA_WINDOW_TAB_VIDEO
} MediaWindowTab;


extern gboolean media_window_rc_parsed;
gboolean media_window_rc_parsed = FALSE;
static gpointer media_window_parent_class = NULL;

#define DEFAULT_STYLE "\nstyle \"custom\"\n{\n    GtkRange::slider-width = 24\n    GtkComboBox::arrow-size = 18\n    GtkComboBox::appears-as-list = 1\n    GtkToolbar::space-size = 0\n    font_name = \"Sans 12\"\n}\n\nwidget_class \"*\" style \"custom\"\n"
GType media_window_get_type (void);
enum  {
	MEDIA_WINDOW_DUMMY_PROPERTY
};
GType media_window_tab_get_type (void);
gboolean media_window_rc_parse (void);
void media_window_lookup_and_set_icon_name (MediaWindow* self, const char* name);
void media_window_toolbar_add_expander (MediaWindow* self);
void media_window_on_quit (MediaWindow* self);
static void _media_window_on_quit_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
void media_window_toolbar_add_quit_button (MediaWindow* self);
void media_window_set_fullscreen (MediaWindow* self, gboolean value);
void media_window_toggle_fullscreen (MediaWindow* self);
gboolean media_window_quit (MediaWindow* self);
static gboolean _media_window_quit_gsource_func (gpointer self);
MediaWindow* media_window_new (void);
MediaWindow* media_window_construct (GType object_type);
static void _media_window_on_quit_gtk_object_destroy (MediaWindow* _sender, gpointer self);
static GObject * media_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void media_window_finalize (GObject* obj);




GType media_window_tab_get_type (void) {
	static GType media_window_tab_type_id = 0;
	if (G_UNLIKELY (media_window_tab_type_id == 0)) {
		static const GEnumValue values[] = {{MEDIA_WINDOW_TAB_LIST, "MEDIA_WINDOW_TAB_LIST", "list"}, {MEDIA_WINDOW_TAB_VIDEO, "MEDIA_WINDOW_TAB_VIDEO", "video"}, {0, NULL, NULL}};
		media_window_tab_type_id = g_enum_register_static ("MediaWindowTab", values);
	}
	return media_window_tab_type_id;
}


gboolean media_window_rc_parse (void) {
	gboolean result;
	gtk_rc_parse_string (DEFAULT_STYLE);
	result = TRUE;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void media_window_lookup_and_set_icon_name (MediaWindow* self, const char* name) {
	GError * _inner_error_;
	GtkIconTheme* theme;
	GtkIconInfo* icon_info;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_inner_error_ = NULL;
	theme = _g_object_ref0 (gtk_icon_theme_get_default ());
	icon_info = gtk_icon_theme_lookup_icon (theme, name, 64, 0);
	if (icon_info != NULL) {
		{
			char* _tmp0_;
			g_print ("%s", _tmp0_ = g_strconcat (gtk_icon_info_get_filename (icon_info), "\n", NULL));
			_g_free0 (_tmp0_);
			gtk_window_set_icon_from_file ((GtkWindow*) self, gtk_icon_info_get_filename (icon_info), &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch0_g_error;
				goto __finally0;
			}
		}
		goto __finally0;
		__catch0_g_error:
		{
			g_clear_error (&_inner_error_);
			_inner_error_ = NULL;
			{
				g_print ("could not load the icon\n");
			}
		}
		__finally0:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (theme);
			_gtk_icon_info_free0 (icon_info);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	} else {
		g_print ("could not find the icon\n");
	}
	_g_object_unref0 (theme);
	_gtk_icon_info_free0 (icon_info);
}


static void _media_window_on_quit_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	media_window_on_quit (self);
}


void media_window_toolbar_add_quit_button (MediaWindow* self) {
	GtkToolButton* quit_button;
	g_return_if_fail (self != NULL);
	media_window_toolbar_add_expander (self);
	quit_button = g_object_ref_sink ((GtkToolButton*) gtk_tool_button_new_from_stock (GTK_STOCK_QUIT));
	gtk_container_add ((GtkContainer*) self->toolbar, (GtkWidget*) quit_button);
	g_signal_connect_object (quit_button, "clicked", (GCallback) _media_window_on_quit_gtk_tool_button_clicked, self, 0);
	_g_object_unref0 (quit_button);
}


void media_window_toolbar_add_expander (MediaWindow* self) {
	GtkSeparatorToolItem* expander_item;
	g_return_if_fail (self != NULL);
	expander_item = g_object_ref_sink ((GtkSeparatorToolItem*) gtk_separator_tool_item_new ());
	gtk_tool_item_set_expand ((GtkToolItem*) expander_item, TRUE);
	gtk_separator_tool_item_set_draw (expander_item, FALSE);
	gtk_container_add ((GtkContainer*) self->toolbar, (GtkWidget*) expander_item);
	_g_object_unref0 (expander_item);
}


void media_window_toggle_fullscreen (MediaWindow* self) {
	g_return_if_fail (self != NULL);
	self->is_fullscreen = !self->is_fullscreen;
	media_window_set_fullscreen (self, self->is_fullscreen);
}


void media_window_set_fullscreen (MediaWindow* self, gboolean value) {
	g_return_if_fail (self != NULL);
	{
		GList* child_collection;
		GList* child_it;
		child_collection = gtk_container_get_children ((GtkContainer*) self->main_box);
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
			GtkWidget* child;
			child = (GtkWidget*) child_it->data;
			{
				if (child != GTK_WIDGET (self->notebook)) {
					gtk_widget_set_visible (child, !value);
				}
			}
		}
		_g_list_free0 (child_collection);
	}
	if (value) {
		gtk_window_fullscreen ((GtkWindow*) self);
	} else {
		gtk_window_unfullscreen ((GtkWindow*) self);
	}
}


static gboolean _media_window_quit_gsource_func (gpointer self) {
	return media_window_quit (self);
}


void media_window_on_quit (MediaWindow* self) {
	g_return_if_fail (self != NULL);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _media_window_quit_gsource_func, g_object_ref (self), g_object_unref);
}


gboolean media_window_quit (MediaWindow* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	gtk_main_quit ();
	result = FALSE;
	return result;
}


MediaWindow* media_window_construct (GType object_type) {
	MediaWindow * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


MediaWindow* media_window_new (void) {
	return media_window_construct (TYPE_MEDIA_WINDOW);
}


static void _media_window_on_quit_gtk_object_destroy (MediaWindow* _sender, gpointer self) {
	media_window_on_quit (self);
}


static GObject * media_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MediaWindow * self;
	parent_class = G_OBJECT_CLASS (media_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MEDIA_WINDOW (obj);
	{
		GtkSettings* settings;
		GtkVBox* _tmp0_;
		GtkToolbar* _tmp1_;
		GtkNotebook* _tmp2_;
		settings = _g_object_ref0 (gtk_widget_get_settings ((GtkWidget*) self));
		g_object_set ((GObject*) settings, "gtk-touchscreen-mode", TRUE, NULL);
		gtk_window_set_default_size ((GtkWindow*) self, 800, 480);
		g_signal_connect_object ((GtkObject*) self, "destroy", (GCallback) _media_window_on_quit_gtk_object_destroy, self, 0);
		self->main_box = (_tmp0_ = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 0)), _g_object_unref0 (self->main_box), _tmp0_);
		gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->main_box);
		self->toolbar = (_tmp1_ = g_object_ref_sink ((GtkToolbar*) gtk_toolbar_new ()), _g_object_unref0 (self->toolbar), _tmp1_);
		gtk_toolbar_set_icon_size (self->toolbar, GTK_ICON_SIZE_DND);
		gtk_box_pack_start ((GtkBox*) self->main_box, (GtkWidget*) self->toolbar, FALSE, FALSE, (guint) 0);
		self->notebook = (_tmp2_ = g_object_ref_sink ((GtkNotebook*) gtk_notebook_new ()), _g_object_unref0 (self->notebook), _tmp2_);
		gtk_notebook_set_show_tabs (self->notebook, FALSE);
		gtk_box_pack_start ((GtkBox*) self->main_box, (GtkWidget*) self->notebook, TRUE, TRUE, (guint) 0);
		gtk_widget_show_all ((GtkWidget*) self->main_box);
		_g_object_unref0 (settings);
	}
	return obj;
}


static void media_window_class_init (MediaWindowClass * klass) {
	media_window_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = media_window_constructor;
	G_OBJECT_CLASS (klass)->finalize = media_window_finalize;
	media_window_rc_parsed = media_window_rc_parse ();
}


static void media_window_instance_init (MediaWindow * self) {
}


static void media_window_finalize (GObject* obj) {
	MediaWindow * self;
	self = MEDIA_WINDOW (obj);
	_g_object_unref0 (self->notebook);
	_g_object_unref0 (self->toolbar);
	_g_object_unref0 (self->main_box);
	G_OBJECT_CLASS (media_window_parent_class)->finalize (obj);
}


GType media_window_get_type (void) {
	static GType media_window_type_id = 0;
	if (media_window_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (MediaWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) media_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MediaWindow), 0, (GInstanceInitFunc) media_window_instance_init, NULL };
		media_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "MediaWindow", &g_define_type_info, 0);
	}
	return media_window_type_id;
}




