/* muxer-app.c generated by valac, the Vala compiler
 * generated from muxer-app.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gst/gst.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MEDIA_WINDOW (media_window_get_type ())
#define MEDIA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MEDIA_WINDOW, MediaWindow))
#define MEDIA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MEDIA_WINDOW, MediaWindowClass))
#define IS_MEDIA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MEDIA_WINDOW))
#define IS_MEDIA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MEDIA_WINDOW))
#define MEDIA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MEDIA_WINDOW, MediaWindowClass))

typedef struct _MediaWindow MediaWindow;
typedef struct _MediaWindowClass MediaWindowClass;

#define TYPE_MUXER_WINDOW (muxer_window_get_type ())
#define MUXER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MUXER_WINDOW, MuxerWindow))
#define MUXER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MUXER_WINDOW, MuxerWindowClass))
#define IS_MUXER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MUXER_WINDOW))
#define IS_MUXER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MUXER_WINDOW))
#define MUXER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MUXER_WINDOW, MuxerWindowClass))

typedef struct _MuxerWindow MuxerWindow;
typedef struct _MuxerWindowClass MuxerWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



MuxerWindow* muxer_window_new (void);
MuxerWindow* muxer_window_construct (GType object_type);
GType media_window_get_type (void);
GType muxer_window_get_type (void);
void _main (char** args, int args_length1);



void _main (char** args, int args_length1) {
	MuxerWindow* window;
	gst_init (&args_length1, &args);
	gtk_init (&args_length1, &args);
	window = g_object_ref_sink (muxer_window_new ());
	gtk_widget_show ((GtkWidget*) window);
	gtk_main ();
	_g_object_unref0 (window);
}


int main (int argc, char ** argv) {
	g_type_init ();
	_main (argv, argc);
	return 0;
}




