/* muxer-control.c generated by valac, the Vala compiler
 * generated from muxer-control.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <common.h>
#include <stdlib.h>
#include <string.h>
#include <gst/gst.h>


#define TYPE_MUXER_CONTROL (muxer_control_get_type ())
#define MUXER_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MUXER_CONTROL, MuxerControl))
#define MUXER_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MUXER_CONTROL, MuxerControlClass))
#define IS_MUXER_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MUXER_CONTROL))
#define IS_MUXER_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MUXER_CONTROL))
#define MUXER_CONTROL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MUXER_CONTROL, MuxerControlClass))

typedef struct _MuxerControl MuxerControl;
typedef struct _MuxerControlClass MuxerControlClass;
typedef struct _MuxerControlPrivate MuxerControlPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _gst_object_unref0(var) ((var == NULL) ? NULL : (var = (gst_object_unref (var), NULL)))

struct _MuxerControl {
	MediaControl parent_instance;
	MuxerControlPrivate * priv;
	char* preview_desc;
	char* record_desc;
	GstElement* overlay;
	GstElement* tee;
	GstElement* videosrc;
	GstElement* audiosrc;
	GstElement* filesrc;
	GstBin* preview_bin;
	GstBin* record_bin;
	GstElement* queue;
	GstClockTime adjust_ts_video;
	GstClockTime adjust_ts_audio;
};

struct _MuxerControlClass {
	MediaControlClass parent_class;
};

struct _MuxerControlPrivate {
	gboolean _recording;
	gboolean _previewing;
};


static gpointer muxer_control_parent_class = NULL;

GType muxer_control_get_type (void);
#define MUXER_CONTROL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MUXER_CONTROL, MuxerControlPrivate))
enum  {
	MUXER_CONTROL_DUMMY_PROPERTY,
	MUXER_CONTROL_PREVIEWING,
	MUXER_CONTROL_RECORDING
};
MuxerControl* muxer_control_new (const char* preview, const char* record);
MuxerControl* muxer_control_construct (GType object_type, const char* preview, const char* record);
void muxer_control_load_preview_bin (MuxerControl* self, GError** error);
void muxer_control_load (MuxerControl* self, GError** error);
void muxer_control_start_preview (MuxerControl* self);
void muxer_control_stop_preview (MuxerControl* self);
void muxer_control_load_record_bin (MuxerControl* self, GError** error);
static inline void _dynamic_set_silent0 (GstElement* obj, gboolean value);
void muxer_control_start_record (MuxerControl* self, GError** error);
void muxer_control_stop_record (MuxerControl* self);
void muxer_control_on_state_changed (MuxerControl* self, GstObject* src, GstState old, GstState current, GstState pending);
static inline void _dynamic_set_silent1 (GstElement* obj, gboolean value);
void muxer_control_on_eos (MuxerControl* self, GstObject* src);
void muxer_control_stop (MuxerControl* self);
void muxer_control_on_error (MuxerControl* self, GstObject* src, GError* e, const char* debug);
gboolean muxer_control_get_previewing (MuxerControl* self);
gboolean muxer_control_get_recording (MuxerControl* self);
static void _muxer_control_on_error_media_control_error_message (MuxerControl* _sender, GstObject* src, GError* _error_, const char* debug, gpointer self);
static void _muxer_control_on_eos_media_control_eos_message (MuxerControl* _sender, GstObject* src, gpointer self);
static void _muxer_control_on_state_changed_media_control_state_changed_message (MuxerControl* _sender, GstObject* src, GstState old, GstState current, GstState pending, gpointer self);
static GObject * muxer_control_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void muxer_control_finalize (GObject* obj);
static void muxer_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);



MuxerControl* muxer_control_construct (GType object_type, const char* preview, const char* record) {
	MuxerControl * self;
	char* _tmp0_;
	char* _tmp1_;
	g_return_val_if_fail (preview != NULL, NULL);
	g_return_val_if_fail (record != NULL, NULL);
	self = g_object_newv (object_type, 0, NULL);
	self->preview_desc = (_tmp0_ = g_strdup (preview), _g_free0 (self->preview_desc), _tmp0_);
	self->record_desc = (_tmp1_ = g_strdup (record), _g_free0 (self->record_desc), _tmp1_);
	return self;
}


MuxerControl* muxer_control_new (const char* preview, const char* record) {
	return muxer_control_construct (TYPE_MUXER_CONTROL, preview, record);
}


void muxer_control_load (MuxerControl* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	muxer_control_load_preview_bin (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


void muxer_control_start_preview (MuxerControl* self) {
	g_return_if_fail (self != NULL);
	gst_element_set_state ((GstElement*) self->preview_bin, GST_STATE_PLAYING);
}


void muxer_control_stop_preview (MuxerControl* self) {
	g_return_if_fail (self != NULL);
	gst_element_set_state ((GstElement*) self->preview_bin, GST_STATE_NULL);
	g_signal_emit_by_name (self, "record-stopped");
}


static gpointer _gst_object_ref0 (gpointer self) {
	return self ? gst_object_ref (self) : NULL;
}


static inline void _dynamic_set_silent0 (GstElement* obj, gboolean value) {
	g_object_set (obj, "silent", value, NULL);
}


void muxer_control_start_record (MuxerControl* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	gst_element_set_state ((GstElement*) self->preview_bin, GST_STATE_NULL);
	muxer_control_load_record_bin (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	gst_bin_add (self->preview_bin, _gst_object_ref0 ((GstElement*) self->record_bin));
	gst_element_link (self->tee, self->queue);
	if (self->overlay != NULL) {
		_dynamic_set_silent0 (self->overlay, FALSE);
	}
	gst_element_set_state ((GstElement*) self->preview_bin, GST_STATE_PLAYING);
}


void muxer_control_stop_record (MuxerControl* self) {
	g_return_if_fail (self != NULL);
	if (!self->priv->_recording) {
		return;
	}
	gst_element_send_event (self->videosrc, gst_event_new_eos ());
	if (self->audiosrc != NULL) {
		gst_element_send_event (self->audiosrc, gst_event_new_eos ());
	}
}


void muxer_control_load_preview_bin (MuxerControl* self, GError** error) {
	GError * _inner_error_;
	GstElement* _tmp0_;
	GstBin* _tmp2_;
	GstElement* _tmp1_;
	GstElement* _tmp3_;
	GstElement* _tmp4_;
	GstElement* _tmp5_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = gst_parse_launch (self->preview_desc, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->preview_bin = (_tmp2_ = (GstBin*) (_tmp1_ = _tmp0_, GST_IS_PIPELINE (_tmp1_) ? ((GstPipeline*) _tmp1_) : NULL), _gst_object_unref0 (self->preview_bin), _tmp2_);
	gst_object_set_name ((GstObject*) self->preview_bin, "preview_bin");
	media_control_set_pipeline ((MediaControl*) self, self->preview_bin);
	self->overlay = (_tmp3_ = gst_bin_get_by_name (self->preview_bin, "overlay"), _gst_object_unref0 (self->overlay), _tmp3_);
	self->videosrc = (_tmp4_ = gst_bin_get_by_name (self->preview_bin, "videosrc"), _gst_object_unref0 (self->videosrc), _tmp4_);
	if ((self->tee = (_tmp5_ = gst_bin_get_by_name (self->preview_bin, "tee"), _gst_object_unref0 (self->tee), _tmp5_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named tee in the preview pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
}


void muxer_control_load_record_bin (MuxerControl* self, GError** error) {
	GError * _inner_error_;
	GstElement* _tmp0_;
	GstBin* _tmp2_;
	GstElement* _tmp1_;
	GstElement* _tmp3_;
	GstElement* _tmp4_;
	GstElement* _tmp5_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = gst_parse_launch (self->record_desc, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->record_bin = (_tmp2_ = (GstBin*) (_tmp1_ = _tmp0_, GST_IS_PIPELINE (_tmp1_) ? ((GstPipeline*) _tmp1_) : NULL), _gst_object_unref0 (self->record_bin), _tmp2_);
	gst_object_set_name ((GstObject*) self->record_bin, "record_bin");
	if ((self->queue = (_tmp3_ = gst_bin_get_by_name (self->record_bin, "queue"), _gst_object_unref0 (self->queue), _tmp3_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named queue in the record pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
	self->audiosrc = (_tmp4_ = gst_bin_get_by_name (self->record_bin, "audiosrc"), _gst_object_unref0 (self->audiosrc), _tmp4_);
	self->filesrc = (_tmp5_ = gst_bin_get_by_name (self->record_bin, "filesrc"), _gst_object_unref0 (self->filesrc), _tmp5_);
}


void muxer_control_on_state_changed (MuxerControl* self, GstObject* src, GstState old, GstState current, GstState pending) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	if (src == GST_OBJECT (self->preview_bin)) {
		gboolean _tmp0_ = FALSE;
		if (old == GST_STATE_PAUSED) {
			_tmp0_ = current == GST_STATE_PLAYING;
		} else {
			_tmp0_ = FALSE;
		}
		if (_tmp0_) {
			self->priv->_previewing = TRUE;
			g_signal_emit_by_name (self, "preview-started");
		}
	} else {
		if (src == GST_OBJECT (self->record_bin)) {
			gboolean _tmp1_ = FALSE;
			if (old == GST_STATE_PAUSED) {
				_tmp1_ = current == GST_STATE_PLAYING;
			} else {
				_tmp1_ = FALSE;
			}
			if (_tmp1_) {
				self->priv->_recording = TRUE;
				g_signal_emit_by_name (self, "record-started");
			}
		}
	}
}


static inline void _dynamic_set_silent1 (GstElement* obj, gboolean value) {
	g_object_set (obj, "silent", value, NULL);
}


void muxer_control_on_eos (MuxerControl* self, GstObject* src) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	if (self->overlay != NULL) {
		_dynamic_set_silent1 (self->overlay, TRUE);
	}
	g_signal_emit_by_name (self, "record-stopped");
	muxer_control_stop_preview (self);
	muxer_control_start_preview (self);
	self->priv->_recording = FALSE;
	;
}


void muxer_control_on_error (MuxerControl* self, GstObject* src, GError* e, const char* debug) {
	char* _tmp0_;
	char* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	g_return_if_fail (debug != NULL);
	g_print ("%s", _tmp0_ = g_strconcat (e->message, "\n", NULL));
	_g_free0 (_tmp0_);
	g_print ("%s", _tmp1_ = g_strconcat (debug, "\n", NULL));
	_g_free0 (_tmp1_);
	muxer_control_stop (self);
}


void muxer_control_stop (MuxerControl* self) {
	g_return_if_fail (self != NULL);
	muxer_control_stop_record (self);
	muxer_control_stop_preview (self);
}


gboolean muxer_control_get_previewing (MuxerControl* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_previewing;
	return result;
}


gboolean muxer_control_get_recording (MuxerControl* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_recording;
	return result;
}


static void _muxer_control_on_error_media_control_error_message (MuxerControl* _sender, GstObject* src, GError* _error_, const char* debug, gpointer self) {
	muxer_control_on_error (self, src, _error_, debug);
}


static void _muxer_control_on_eos_media_control_eos_message (MuxerControl* _sender, GstObject* src, gpointer self) {
	muxer_control_on_eos (self, src);
}


static void _muxer_control_on_state_changed_media_control_state_changed_message (MuxerControl* _sender, GstObject* src, GstState old, GstState current, GstState pending, gpointer self) {
	muxer_control_on_state_changed (self, src, old, current, pending);
}


static GObject * muxer_control_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MuxerControl * self;
	parent_class = G_OBJECT_CLASS (muxer_control_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MUXER_CONTROL (obj);
	{
		g_signal_connect_object ((MediaControl*) self, "error-message", (GCallback) _muxer_control_on_error_media_control_error_message, self, 0);
		g_signal_connect_object ((MediaControl*) self, "eos-message", (GCallback) _muxer_control_on_eos_media_control_eos_message, self, 0);
		g_signal_connect_object ((MediaControl*) self, "state-changed-message", (GCallback) _muxer_control_on_state_changed_media_control_state_changed_message, self, 0);
	}
	return obj;
}


static void muxer_control_class_init (MuxerControlClass * klass) {
	muxer_control_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MuxerControlPrivate));
	G_OBJECT_CLASS (klass)->get_property = muxer_control_get_property;
	G_OBJECT_CLASS (klass)->constructor = muxer_control_constructor;
	G_OBJECT_CLASS (klass)->finalize = muxer_control_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MUXER_CONTROL_PREVIEWING, g_param_spec_boolean ("previewing", "previewing", "previewing", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MUXER_CONTROL_RECORDING, g_param_spec_boolean ("recording", "recording", "recording", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("preview_started", TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("preview_stopped", TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("record_started", TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("record_stopped", TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void muxer_control_instance_init (MuxerControl * self) {
	self->priv = MUXER_CONTROL_GET_PRIVATE (self);
}


static void muxer_control_finalize (GObject* obj) {
	MuxerControl * self;
	self = MUXER_CONTROL (obj);
	{
		muxer_control_stop (self);
	}
	_g_free0 (self->preview_desc);
	_g_free0 (self->record_desc);
	_gst_object_unref0 (self->overlay);
	_gst_object_unref0 (self->tee);
	_gst_object_unref0 (self->videosrc);
	_gst_object_unref0 (self->audiosrc);
	_gst_object_unref0 (self->filesrc);
	_gst_object_unref0 (self->preview_bin);
	_gst_object_unref0 (self->record_bin);
	_gst_object_unref0 (self->queue);
	G_OBJECT_CLASS (muxer_control_parent_class)->finalize (obj);
}


GType muxer_control_get_type (void) {
	static GType muxer_control_type_id = 0;
	if (muxer_control_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (MuxerControlClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) muxer_control_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MuxerControl), 0, (GInstanceInitFunc) muxer_control_instance_init, NULL };
		muxer_control_type_id = g_type_register_static (TYPE_MEDIA_CONTROL, "MuxerControl", &g_define_type_info, 0);
	}
	return muxer_control_type_id;
}


static void muxer_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MuxerControl * self;
	self = MUXER_CONTROL (object);
	switch (property_id) {
		case MUXER_CONTROL_PREVIEWING:
		g_value_set_boolean (value, muxer_control_get_previewing (self));
		break;
		case MUXER_CONTROL_RECORDING:
		g_value_set_boolean (value, muxer_control_get_recording (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




