/* muxer-window.c generated by valac, the Vala compiler
 * generated from muxer-window.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gst/gst.h>


#define TYPE_MUXER_COMBO_COL (muxer_combo_col_get_type ())

#define TYPE_MUXER_WINDOW (muxer_window_get_type ())
#define MUXER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MUXER_WINDOW, MuxerWindow))
#define MUXER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MUXER_WINDOW, MuxerWindowClass))
#define IS_MUXER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MUXER_WINDOW))
#define IS_MUXER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MUXER_WINDOW))
#define MUXER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MUXER_WINDOW, MuxerWindowClass))

typedef struct _MuxerWindow MuxerWindow;
typedef struct _MuxerWindowClass MuxerWindowClass;
typedef struct _MuxerWindowPrivate MuxerWindowPrivate;

#define TYPE_MUXER_CONTROL (muxer_control_get_type ())
#define MUXER_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MUXER_CONTROL, MuxerControl))
#define MUXER_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MUXER_CONTROL, MuxerControlClass))
#define IS_MUXER_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MUXER_CONTROL))
#define IS_MUXER_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MUXER_CONTROL))
#define MUXER_CONTROL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MUXER_CONTROL, MuxerControlClass))

typedef struct _MuxerControl MuxerControl;
typedef struct _MuxerControlClass MuxerControlClass;

#define TYPE_VIDEO_AREA (video_area_get_type ())
#define VIDEO_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VIDEO_AREA, VideoArea))
#define VIDEO_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VIDEO_AREA, VideoAreaClass))
#define IS_VIDEO_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VIDEO_AREA))
#define IS_VIDEO_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VIDEO_AREA))
#define VIDEO_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VIDEO_AREA, VideoAreaClass))

typedef struct _VideoArea VideoArea;
typedef struct _VideoAreaClass VideoAreaClass;

#define TYPE_DEBUG_DIALOG (debug_dialog_get_type ())
#define DEBUG_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DEBUG_DIALOG, DebugDialog))
#define DEBUG_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DEBUG_DIALOG, DebugDialogClass))
#define IS_DEBUG_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DEBUG_DIALOG))
#define IS_DEBUG_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DEBUG_DIALOG))
#define DEBUG_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DEBUG_DIALOG, DebugDialogClass))

typedef struct _DebugDialog DebugDialog;
typedef struct _DebugDialogClass DebugDialogClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_CONTROL (control_get_type ())
#define CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONTROL, Control))
#define IS_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONTROL))
#define CONTROL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_CONTROL, ControlIface))

typedef struct _Control Control;
typedef struct _ControlIface ControlIface;

#define TYPE_MUXER_CONFIG_PARSER (muxer_config_parser_get_type ())
#define MUXER_CONFIG_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MUXER_CONFIG_PARSER, MuxerConfigParser))
#define MUXER_CONFIG_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MUXER_CONFIG_PARSER, MuxerConfigParserClass))
#define IS_MUXER_CONFIG_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MUXER_CONFIG_PARSER))
#define IS_MUXER_CONFIG_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MUXER_CONFIG_PARSER))
#define MUXER_CONFIG_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MUXER_CONFIG_PARSER, MuxerConfigParserClass))

typedef struct _MuxerConfigParser MuxerConfigParser;
typedef struct _MuxerConfigParserClass MuxerConfigParserClass;
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))

typedef enum  {
	MUXER_COMBO_COL_GROUP,
	MUXER_COMBO_COL_PREVIEW,
	MUXER_COMBO_COL_RECORD
} MuxerComboCol;

struct _MuxerWindow {
	GtkWindow parent_instance;
	MuxerWindowPrivate * priv;
	GtkComboBox* combo_box;
	GtkListStore* combo_model;
	GtkFileChooserButton* chooser_button;
	GtkButton* record_button;
	GtkButton* quit_button;
	GtkToggleButton* probe_button;
	GtkButton* stop_button;
	MuxerControl* muxer_control;
	VideoArea* video_area;
	DebugDialog* debug_dialog;
};

struct _MuxerWindowClass {
	GtkWindowClass parent_class;
};

struct _ControlIface {
	GTypeInterface parent_iface;
	GstBus* (*get_bus) (Control* self);
};


static gpointer muxer_window_parent_class = NULL;

#define TITLE "MuxerApp"
#define USE_BUFFER_PROBE FALSE
GType muxer_combo_col_get_type (void);
GType muxer_window_get_type (void);
GType muxer_control_get_type (void);
GType video_area_get_type (void);
GType debug_dialog_get_type (void);
enum  {
	MUXER_WINDOW_DUMMY_PROPERTY
};
#define DEFAULT_WIDTH 800
#define DEFAULT_HEIGHT 480
void muxer_window_on_quit (MuxerWindow* self);
static void _muxer_window_on_quit_gtk_object_destroy (MuxerWindow* _sender, gpointer self);
void muxer_window_on_chooser_file_set (MuxerWindow* self);
static void _muxer_window_on_chooser_file_set_gtk_file_chooser_button_file_set (GtkFileChooserButton* _sender, gpointer self);
void muxer_window_on_combo_changed (MuxerWindow* self);
static void _muxer_window_on_combo_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
void muxer_window_on_record (MuxerWindow* self);
static void _muxer_window_on_record_gtk_button_clicked (GtkButton* _sender, gpointer self);
#define ICON_SIZE GTK_ICON_SIZE_DND
void muxer_window_on_stop (MuxerWindow* self);
static void _muxer_window_on_stop_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _muxer_window_on_quit_gtk_button_clicked (GtkButton* _sender, gpointer self);
VideoArea* video_area_new (void);
VideoArea* video_area_construct (GType object_type);
void muxer_window_setup_widgets (MuxerWindow* self);
gboolean muxer_window_get_pipelines (MuxerWindow* self, char** preview, char** record);
void muxer_window_shutdown (MuxerWindow* self);
MuxerControl* muxer_control_new (const char* preview, const char* record);
MuxerControl* muxer_control_construct (GType object_type, const char* preview, const char* record);
void muxer_control_enable_buffer_probe (MuxerControl* self, gboolean enabled);
void muxer_window_on_control_error (MuxerWindow* self, GError* _error_, const char* debug);
static void _muxer_window_on_control_error_muxer_control_error (MuxerControl* _sender, GError* e, const char* debug, gpointer self);
void muxer_control_load (MuxerControl* self, GError** error);
void show_error (GError* _error_);
GType control_get_type (void);
void video_area_set_control (VideoArea* self, Control* control);
void muxer_control_start_preview (MuxerControl* self);
void muxer_window_record_stopped (MuxerWindow* self);
static void _muxer_window_record_stopped_muxer_control_eos (MuxerControl* _sender, gpointer self);
void muxer_control_start_record (MuxerControl* self, GError** error);
void muxer_control_stop_record (MuxerControl* self);
void muxer_control_shutdown (MuxerControl* self);
MuxerConfigParser* muxer_config_parser_new (void);
MuxerConfigParser* muxer_config_parser_construct (GType object_type);
GType muxer_config_parser_get_type (void);
gboolean muxer_config_parser_parse_file (MuxerConfigParser* self, const char* file, GKeyFile** key_file, GError** error);
void muxer_window_show_debug (MuxerWindow* self, GError* _error_, const char* debug);
void muxer_window_setup_debug_dialog (MuxerWindow* self);
void debug_dialog_add_error_debug (DebugDialog* self, GError* _error_, const char* debug);
DebugDialog* debug_dialog_new (GtkWindow* parent);
DebugDialog* debug_dialog_construct (GType object_type, GtkWindow* parent);
void muxer_window_on_debug_dialog_closed (MuxerWindow* self);
static void _muxer_window_on_debug_dialog_closed_debug_dialog_closed (DebugDialog* _sender, gpointer self);
MuxerWindow* muxer_window_new (void);
MuxerWindow* muxer_window_construct (GType object_type);
static GObject * muxer_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void muxer_window_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);




GType muxer_combo_col_get_type (void) {
	static GType muxer_combo_col_type_id = 0;
	if (G_UNLIKELY (muxer_combo_col_type_id == 0)) {
		static const GEnumValue values[] = {{MUXER_COMBO_COL_GROUP, "MUXER_COMBO_COL_GROUP", "group"}, {MUXER_COMBO_COL_PREVIEW, "MUXER_COMBO_COL_PREVIEW", "preview"}, {MUXER_COMBO_COL_RECORD, "MUXER_COMBO_COL_RECORD", "record"}, {0, NULL, NULL}};
		muxer_combo_col_type_id = g_enum_register_static ("MuxerComboCol", values);
	}
	return muxer_combo_col_type_id;
}


static void _muxer_window_on_quit_gtk_object_destroy (MuxerWindow* _sender, gpointer self) {
	muxer_window_on_quit (self);
}


static void _muxer_window_on_chooser_file_set_gtk_file_chooser_button_file_set (GtkFileChooserButton* _sender, gpointer self) {
	muxer_window_on_chooser_file_set (self);
}


static void _muxer_window_on_combo_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	muxer_window_on_combo_changed (self);
}


static void _muxer_window_on_record_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	muxer_window_on_record (self);
}


static void _muxer_window_on_stop_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	muxer_window_on_stop (self);
}


static void _muxer_window_on_quit_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	muxer_window_on_quit (self);
}


void muxer_window_setup_widgets (MuxerWindow* self) {
	GtkVBox* main_box;
	GtkHBox* buttons_box;
	GtkFileChooserButton* _tmp0_;
	GtkFileFilter* file_filter;
	GType s;
	GtkListStore* _tmp1_;
	GtkComboBox* _tmp2_;
	GtkCellRendererText* renderer;
	GtkButton* _tmp3_;
	GtkImage* record_image;
	GtkToggleButton* _tmp4_;
	GtkImage* probe_image;
	GtkButton* _tmp5_;
	GtkImage* stop_image;
	GtkButton* _tmp6_;
	GtkImage* quit_image;
	VideoArea* _tmp7_;
	g_return_if_fail (self != NULL);
	gtk_window_set_default_size ((GtkWindow*) self, DEFAULT_WIDTH, DEFAULT_HEIGHT);
	g_signal_connect_object ((GtkObject*) self, "destroy", (GCallback) _muxer_window_on_quit_gtk_object_destroy, self, 0);
	main_box = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 6));
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) main_box);
	buttons_box = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 6));
	gtk_box_pack_start ((GtkBox*) main_box, (GtkWidget*) buttons_box, FALSE, FALSE, (guint) 0);
	self->chooser_button = (_tmp0_ = g_object_ref_sink ((GtkFileChooserButton*) gtk_file_chooser_button_new ("Config file", GTK_FILE_CHOOSER_ACTION_OPEN)), _g_object_unref0 (self->chooser_button), _tmp0_);
	gtk_box_pack_start ((GtkBox*) buttons_box, (GtkWidget*) self->chooser_button, TRUE, TRUE, (guint) 0);
	g_signal_connect_object (self->chooser_button, "file-set", (GCallback) _muxer_window_on_chooser_file_set_gtk_file_chooser_button_file_set, self, 0);
	file_filter = g_object_ref_sink (gtk_file_filter_new ());
	gtk_file_filter_set_name (file_filter, "Config files");
	gtk_file_filter_add_pattern (file_filter, "*.ini");
	gtk_file_filter_add_pattern (file_filter, "*.xml");
	gtk_file_chooser_add_filter ((GtkFileChooser*) self->chooser_button, file_filter);
	s = G_TYPE_STRING;
	self->combo_model = (_tmp1_ = gtk_list_store_new (3, s, s, s, NULL), _g_object_unref0 (self->combo_model), _tmp1_);
	self->combo_box = (_tmp2_ = g_object_ref_sink ((GtkComboBox*) gtk_combo_box_new_with_model ((GtkTreeModel*) self->combo_model)), _g_object_unref0 (self->combo_box), _tmp2_);
	gtk_box_pack_start ((GtkBox*) buttons_box, (GtkWidget*) self->combo_box, FALSE, FALSE, (guint) 0);
	renderer = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
	gtk_cell_layout_pack_start ((GtkCellLayout*) self->combo_box, (GtkCellRenderer*) renderer, TRUE);
	gtk_cell_layout_set_attributes ((GtkCellLayout*) self->combo_box, (GtkCellRenderer*) renderer, "text", MUXER_COMBO_COL_GROUP, NULL, NULL);
	g_signal_connect_object (self->combo_box, "changed", (GCallback) _muxer_window_on_combo_changed_gtk_combo_box_changed, self, 0);
	self->record_button = (_tmp3_ = g_object_ref_sink ((GtkButton*) gtk_button_new ()), _g_object_unref0 (self->record_button), _tmp3_);
	gtk_box_pack_start ((GtkBox*) buttons_box, (GtkWidget*) self->record_button, FALSE, FALSE, (guint) 0);
	gtk_widget_set_sensitive ((GtkWidget*) self->record_button, FALSE);
	g_signal_connect_object (self->record_button, "clicked", (GCallback) _muxer_window_on_record_gtk_button_clicked, self, 0);
	record_image = g_object_ref_sink ((GtkImage*) gtk_image_new ());
	gtk_container_add ((GtkContainer*) self->record_button, (GtkWidget*) record_image);
	gtk_image_set_from_stock (record_image, GTK_STOCK_MEDIA_RECORD, ICON_SIZE);
	self->probe_button = (_tmp4_ = g_object_ref_sink ((GtkToggleButton*) gtk_toggle_button_new ()), _g_object_unref0 (self->probe_button), _tmp4_);
	gtk_box_pack_start ((GtkBox*) buttons_box, (GtkWidget*) self->probe_button, FALSE, FALSE, (guint) 0);
	probe_image = g_object_ref_sink ((GtkImage*) gtk_image_new ());
	gtk_container_add ((GtkContainer*) self->probe_button, (GtkWidget*) probe_image);
	gtk_image_set_from_stock (probe_image, GTK_STOCK_CONVERT, ICON_SIZE);
	self->stop_button = (_tmp5_ = g_object_ref_sink ((GtkButton*) gtk_button_new ()), _g_object_unref0 (self->stop_button), _tmp5_);
	gtk_box_pack_start ((GtkBox*) buttons_box, (GtkWidget*) self->stop_button, FALSE, FALSE, (guint) 0);
	gtk_widget_set_sensitive ((GtkWidget*) self->stop_button, FALSE);
	g_signal_connect_object (self->stop_button, "clicked", (GCallback) _muxer_window_on_stop_gtk_button_clicked, self, 0);
	stop_image = g_object_ref_sink ((GtkImage*) gtk_image_new ());
	gtk_container_add ((GtkContainer*) self->stop_button, (GtkWidget*) stop_image);
	gtk_image_set_from_stock (stop_image, GTK_STOCK_MEDIA_STOP, ICON_SIZE);
	self->quit_button = (_tmp6_ = g_object_ref_sink ((GtkButton*) gtk_button_new ()), _g_object_unref0 (self->quit_button), _tmp6_);
	gtk_box_pack_start ((GtkBox*) buttons_box, (GtkWidget*) self->quit_button, FALSE, FALSE, (guint) 0);
	g_signal_connect_object (self->quit_button, "clicked", (GCallback) _muxer_window_on_quit_gtk_button_clicked, self, 0);
	quit_image = g_object_ref_sink ((GtkImage*) gtk_image_new ());
	gtk_container_add ((GtkContainer*) self->quit_button, (GtkWidget*) quit_image);
	gtk_image_set_from_stock (quit_image, GTK_STOCK_QUIT, ICON_SIZE);
	self->video_area = (_tmp7_ = g_object_ref_sink (video_area_new ()), _g_object_unref0 (self->video_area), _tmp7_);
	gtk_box_pack_start ((GtkBox*) main_box, (GtkWidget*) self->video_area, TRUE, TRUE, (guint) 6);
	gtk_widget_show_all ((GtkWidget*) main_box);
	gtk_widget_realize ((GtkWidget*) self->video_area);
	_g_object_unref0 (main_box);
	_g_object_unref0 (buttons_box);
	_g_object_unref0 (file_filter);
	_g_object_unref0 (renderer);
	_g_object_unref0 (record_image);
	_g_object_unref0 (probe_image);
	_g_object_unref0 (stop_image);
	_g_object_unref0 (quit_image);
}


static void _muxer_window_on_control_error_muxer_control_error (MuxerControl* _sender, GError* e, const char* debug, gpointer self) {
	muxer_window_on_control_error (self, e, debug);
}


static void _muxer_window_record_stopped_muxer_control_eos (MuxerControl* _sender, gpointer self) {
	muxer_window_record_stopped (self);
}


void muxer_window_on_combo_changed (MuxerWindow* self) {
	GError * _inner_error_;
	char* preview;
	char* record;
	char* _tmp5_;
	gboolean _tmp4_;
	char* _tmp3_ = NULL;
	char* _tmp2_;
	gboolean _tmp1_;
	char* _tmp0_ = NULL;
	MuxerControl* _tmp6_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	preview = NULL;
	record = NULL;
	if (!(_tmp4_ = (_tmp1_ = muxer_window_get_pipelines (self, &_tmp0_, &_tmp3_), preview = (_tmp2_ = _tmp0_, _g_free0 (preview), _tmp2_), _tmp1_), record = (_tmp5_ = _tmp3_, _g_free0 (record), _tmp5_), _tmp4_)) {
		g_print ("Could not get the pipelines\n");
		_g_free0 (preview);
		_g_free0 (record);
		return;
	}
	muxer_window_shutdown (self);
	self->muxer_control = (_tmp6_ = muxer_control_new (preview, record), _g_object_unref0 (self->muxer_control), _tmp6_);
	muxer_control_enable_buffer_probe (self->muxer_control, gtk_toggle_button_get_active (self->probe_button));
	g_signal_connect_object (self->muxer_control, "error", (GCallback) _muxer_window_on_control_error_muxer_control_error, self, 0);
	{
		muxer_control_load (self->muxer_control, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
			goto __finally0;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			show_error (e);
			_g_error_free0 (e);
			_g_free0 (preview);
			_g_free0 (record);
			return;
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_free0 (preview);
		_g_free0 (record);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	video_area_set_control (self->video_area, (Control*) self->muxer_control);
	muxer_control_start_preview (self->muxer_control);
	g_signal_connect_object (self->muxer_control, "eos", (GCallback) _muxer_window_record_stopped_muxer_control_eos, self, 0);
	gtk_widget_set_sensitive ((GtkWidget*) self->record_button, TRUE);
	_g_free0 (preview);
	_g_free0 (record);
}


void muxer_window_on_record (MuxerWindow* self) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	{
		muxer_control_start_record (self->muxer_control, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch1_g_error;
			goto __finally1;
		}
		gtk_widget_set_sensitive ((GtkWidget*) self->stop_button, TRUE);
		gtk_widget_set_sensitive ((GtkWidget*) self->record_button, FALSE);
		gtk_widget_set_sensitive ((GtkWidget*) self->quit_button, FALSE);
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			show_error (e);
			_g_error_free0 (e);
		}
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void muxer_window_on_stop (MuxerWindow* self) {
	g_return_if_fail (self != NULL);
	muxer_control_stop_record (self->muxer_control);
	gtk_widget_set_sensitive ((GtkWidget*) self->stop_button, FALSE);
}


void muxer_window_record_stopped (MuxerWindow* self) {
	g_return_if_fail (self != NULL);
	gtk_widget_set_sensitive ((GtkWidget*) self->quit_button, TRUE);
	gtk_widget_set_sensitive ((GtkWidget*) self->record_button, TRUE);
}


void muxer_window_on_quit (MuxerWindow* self) {
	g_return_if_fail (self != NULL);
	muxer_window_shutdown (self);
	gtk_main_quit ();
}


void muxer_window_shutdown (MuxerWindow* self) {
	MuxerControl* _tmp0_;
	g_return_if_fail (self != NULL);
	if (self->muxer_control == NULL) {
		return;
	}
	muxer_control_shutdown (self->muxer_control);
	self->muxer_control = (_tmp0_ = NULL, _g_object_unref0 (self->muxer_control), _tmp0_);
}


void muxer_window_on_chooser_file_set (MuxerWindow* self) {
	GError * _inner_error_;
	char* config_file;
	GKeyFile* key_file;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	config_file = gtk_file_chooser_get_filename ((GtkFileChooser*) self->chooser_button);
	key_file = g_key_file_new ();
	{
		if (g_str_has_suffix (config_file, ".ini")) {
			g_key_file_load_from_file (key_file, config_file, G_KEY_FILE_NONE, &_inner_error_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_FILE_ERROR) {
					goto __catch2_g_file_error;
				}
				if (_inner_error_->domain == G_KEY_FILE_ERROR) {
					goto __catch2_g_key_file_error;
				}
				if (_inner_error_->domain == G_MARKUP_ERROR) {
					goto __catch2_g_markup_error;
				}
				goto __finally2;
			}
		} else {
			MuxerConfigParser* xml_parser;
			xml_parser = muxer_config_parser_new ();
			muxer_config_parser_parse_file (xml_parser, config_file, &key_file, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (xml_parser);
				if (_inner_error_->domain == G_FILE_ERROR) {
					goto __catch2_g_file_error;
				}
				if (_inner_error_->domain == G_KEY_FILE_ERROR) {
					goto __catch2_g_key_file_error;
				}
				if (_inner_error_->domain == G_MARKUP_ERROR) {
					goto __catch2_g_markup_error;
				}
				goto __finally2;
			}
			_g_object_unref0 (xml_parser);
		}
	}
	goto __finally2;
	__catch2_g_file_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			show_error (e);
			_g_error_free0 (e);
			_g_free0 (config_file);
			_g_key_file_free0 (key_file);
			return;
		}
	}
	goto __finally2;
	__catch2_g_key_file_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			show_error (e);
			_g_error_free0 (e);
			_g_free0 (config_file);
			_g_key_file_free0 (key_file);
			return;
		}
	}
	goto __finally2;
	__catch2_g_markup_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			show_error (e);
			_g_error_free0 (e);
			_g_free0 (config_file);
			_g_key_file_free0 (key_file);
			return;
		}
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_free0 (config_file);
		_g_key_file_free0 (key_file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	{
		gtk_list_store_clear (self->combo_model);
		{
			gsize _tmp0_;
			char** group_collection;
			int group_collection_length1;
			int group_it;
			group_collection = g_key_file_get_groups (key_file, &_tmp0_);
			group_collection_length1 = _tmp0_;
			for (group_it = 0; group_it < _tmp0_; group_it = group_it + 1) {
				char* group;
				group = g_strdup (group_collection[group_it]);
				{
					char* preview;
					char* record;
					gboolean _tmp1_ = FALSE;
					preview = g_key_file_get_string (key_file, group, "preview", &_inner_error_);
					if (_inner_error_ != NULL) {
						_g_free0 (group);
						group_collection = (_vala_array_free (group_collection, group_collection_length1, (GDestroyNotify) g_free), NULL);
						if (_inner_error_->domain == G_KEY_FILE_ERROR) {
							goto __catch3_g_key_file_error;
						}
						goto __finally3;
					}
					record = g_key_file_get_string (key_file, group, "record", &_inner_error_);
					if (_inner_error_ != NULL) {
						_g_free0 (group);
						_g_free0 (preview);
						group_collection = (_vala_array_free (group_collection, group_collection_length1, (GDestroyNotify) g_free), NULL);
						if (_inner_error_->domain == G_KEY_FILE_ERROR) {
							goto __catch3_g_key_file_error;
						}
						goto __finally3;
					}
					if (preview == NULL) {
						_tmp1_ = TRUE;
					} else {
						_tmp1_ = record == NULL;
					}
					if (_tmp1_) {
						_g_free0 (group);
						_g_free0 (preview);
						_g_free0 (record);
						continue;
					}
					gtk_list_store_insert_with_values (self->combo_model, NULL, -1, MUXER_COMBO_COL_GROUP, group, MUXER_COMBO_COL_PREVIEW, preview, MUXER_COMBO_COL_RECORD, record, -1, -1);
					_g_free0 (group);
					_g_free0 (preview);
					_g_free0 (record);
				}
			}
			group_collection = (_vala_array_free (group_collection, group_collection_length1, (GDestroyNotify) g_free), NULL);
		}
	}
	goto __finally3;
	__catch3_g_key_file_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			show_error (e);
			_g_error_free0 (e);
		}
	}
	__finally3:
	if (_inner_error_ != NULL) {
		_g_free0 (config_file);
		_g_key_file_free0 (key_file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (config_file);
	_g_key_file_free0 (key_file);
}


gboolean muxer_window_get_pipelines (MuxerWindow* self, char** preview, char** record) {
	gboolean result;
	GtkTreeIter iter = {0};
	g_return_val_if_fail (self != NULL, FALSE);
	if (preview != NULL) {
		*preview = NULL;
	}
	if (record != NULL) {
		*record = NULL;
	}
	if (!gtk_combo_box_get_active_iter (self->combo_box, &iter)) {
		result = FALSE;
		return result;
	}
	gtk_tree_model_get ((GtkTreeModel*) self->combo_model, &iter, MUXER_COMBO_COL_PREVIEW, preview, MUXER_COMBO_COL_RECORD, record, -1, -1);
	result = TRUE;
	return result;
}


void muxer_window_on_control_error (MuxerWindow* self, GError* _error_, const char* debug) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (debug != NULL);
	muxer_window_show_debug (self, _error_, debug);
}


void muxer_window_show_debug (MuxerWindow* self, GError* _error_, const char* debug) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (debug != NULL);
	muxer_window_setup_debug_dialog (self);
	debug_dialog_add_error_debug (self->debug_dialog, _error_, debug);
}


static void _muxer_window_on_debug_dialog_closed_debug_dialog_closed (DebugDialog* _sender, gpointer self) {
	muxer_window_on_debug_dialog_closed (self);
}


void muxer_window_setup_debug_dialog (MuxerWindow* self) {
	g_return_if_fail (self != NULL);
	if (self->debug_dialog == NULL) {
		DebugDialog* _tmp0_;
		self->debug_dialog = (_tmp0_ = g_object_ref_sink (debug_dialog_new ((GtkWindow*) self)), _g_object_unref0 (self->debug_dialog), _tmp0_);
		g_signal_connect_object (self->debug_dialog, "closed", (GCallback) _muxer_window_on_debug_dialog_closed_debug_dialog_closed, self, 0);
		gtk_widget_show_all ((GtkWidget*) self->debug_dialog);
	}
}


void muxer_window_on_debug_dialog_closed (MuxerWindow* self) {
	DebugDialog* _tmp0_;
	g_return_if_fail (self != NULL);
	muxer_window_shutdown (self);
	self->debug_dialog = (_tmp0_ = NULL, _g_object_unref0 (self->debug_dialog), _tmp0_);
}


MuxerWindow* muxer_window_construct (GType object_type) {
	MuxerWindow * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


MuxerWindow* muxer_window_new (void) {
	return muxer_window_construct (TYPE_MUXER_WINDOW);
}


static GObject * muxer_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MuxerWindow * self;
	parent_class = G_OBJECT_CLASS (muxer_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MUXER_WINDOW (obj);
	{
		muxer_window_setup_widgets (self);
	}
	return obj;
}


static void muxer_window_class_init (MuxerWindowClass * klass) {
	muxer_window_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = muxer_window_constructor;
	G_OBJECT_CLASS (klass)->finalize = muxer_window_finalize;
}


static void muxer_window_instance_init (MuxerWindow * self) {
}


static void muxer_window_finalize (GObject* obj) {
	MuxerWindow * self;
	self = MUXER_WINDOW (obj);
	_g_object_unref0 (self->combo_box);
	_g_object_unref0 (self->combo_model);
	_g_object_unref0 (self->chooser_button);
	_g_object_unref0 (self->record_button);
	_g_object_unref0 (self->quit_button);
	_g_object_unref0 (self->probe_button);
	_g_object_unref0 (self->stop_button);
	_g_object_unref0 (self->muxer_control);
	_g_object_unref0 (self->video_area);
	_g_object_unref0 (self->debug_dialog);
	G_OBJECT_CLASS (muxer_window_parent_class)->finalize (obj);
}


GType muxer_window_get_type (void) {
	static GType muxer_window_type_id = 0;
	if (muxer_window_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (MuxerWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) muxer_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MuxerWindow), 0, (GInstanceInitFunc) muxer_window_instance_init, NULL };
		muxer_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "MuxerWindow", &g_define_type_info, 0);
	}
	return muxer_window_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}




