/* muxer-control.c generated by valac, the Vala compiler
 * generated from muxer-control.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <common.h>
#include <stdlib.h>
#include <string.h>
#include <gst/gst.h>


#define OMAP_TYPE_MUXER_CONTROL (omap_muxer_control_get_type ())
#define OMAP_MUXER_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMAP_TYPE_MUXER_CONTROL, OmapMuxerControl))
#define OMAP_MUXER_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMAP_TYPE_MUXER_CONTROL, OmapMuxerControlClass))
#define OMAP_IS_MUXER_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMAP_TYPE_MUXER_CONTROL))
#define OMAP_IS_MUXER_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMAP_TYPE_MUXER_CONTROL))
#define OMAP_MUXER_CONTROL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMAP_TYPE_MUXER_CONTROL, OmapMuxerControlClass))

typedef struct _OmapMuxerControl OmapMuxerControl;
typedef struct _OmapMuxerControlClass OmapMuxerControlClass;
typedef struct _OmapMuxerControlPrivate OmapMuxerControlPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _gst_object_unref0(var) ((var == NULL) ? NULL : (var = (gst_object_unref (var), NULL)))

struct _OmapMuxerControl {
	OmapMediaControl parent_instance;
	OmapMuxerControlPrivate * priv;
	char* preview_desc;
	char* record_desc;
	GstElement* overlay;
	GstElement* tee;
	GstElement* videosrc;
	GstElement* audiosrc;
	GstElement* filesrc;
	GstBin* preview_bin;
	GstBin* record_bin;
	GstElement* queue;
	GstClockTime adjust_ts_video;
	GstClockTime adjust_ts_audio;
};

struct _OmapMuxerControlClass {
	OmapMediaControlClass parent_class;
};

struct _OmapMuxerControlPrivate {
	gboolean _recording;
	gboolean _previewing;
};


static gpointer omap_muxer_control_parent_class = NULL;

GType omap_muxer_control_get_type (void);
#define OMAP_MUXER_CONTROL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), OMAP_TYPE_MUXER_CONTROL, OmapMuxerControlPrivate))
enum  {
	OMAP_MUXER_CONTROL_DUMMY_PROPERTY,
	OMAP_MUXER_CONTROL_PREVIEWING,
	OMAP_MUXER_CONTROL_RECORDING
};
OmapMuxerControl* omap_muxer_control_new (const char* preview, const char* record);
OmapMuxerControl* omap_muxer_control_construct (GType object_type, const char* preview, const char* record);
void omap_muxer_control_load_preview_bin (OmapMuxerControl* self, GError** error);
void omap_muxer_control_load (OmapMuxerControl* self, GError** error);
void omap_muxer_control_start_preview (OmapMuxerControl* self);
void omap_muxer_control_stop_preview (OmapMuxerControl* self);
void omap_muxer_control_load_record_bin (OmapMuxerControl* self, GError** error);
static inline void _dynamic_set_silent0 (GstElement* obj, gboolean value);
void omap_muxer_control_start_record (OmapMuxerControl* self, GError** error);
void omap_muxer_control_stop_record (OmapMuxerControl* self);
void omap_muxer_control_on_state_changed (OmapMuxerControl* self, GstObject* src, GstState old, GstState current, GstState pending);
static inline void _dynamic_set_silent1 (GstElement* obj, gboolean value);
void omap_muxer_control_on_eos (OmapMuxerControl* self, GstObject* src);
void omap_muxer_control_stop (OmapMuxerControl* self);
gboolean omap_muxer_control_get_previewing (OmapMuxerControl* self);
gboolean omap_muxer_control_get_recording (OmapMuxerControl* self);
static void _omap_muxer_control_on_eos_omap_media_control_eos_message (OmapMuxerControl* _sender, GstObject* src, gpointer self);
static void _omap_muxer_control_on_state_changed_omap_media_control_state_changed_message (OmapMuxerControl* _sender, GstObject* src, GstState old, GstState current, GstState pending, gpointer self);
static GObject * omap_muxer_control_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void omap_muxer_control_finalize (GObject* obj);
static void omap_muxer_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);



OmapMuxerControl* omap_muxer_control_construct (GType object_type, const char* preview, const char* record) {
	OmapMuxerControl * self;
	char* _tmp0_;
	char* _tmp1_;
	g_return_val_if_fail (preview != NULL, NULL);
	g_return_val_if_fail (record != NULL, NULL);
	self = g_object_newv (object_type, 0, NULL);
	self->preview_desc = (_tmp0_ = g_strdup (preview), _g_free0 (self->preview_desc), _tmp0_);
	self->record_desc = (_tmp1_ = g_strdup (record), _g_free0 (self->record_desc), _tmp1_);
	return self;
}


OmapMuxerControl* omap_muxer_control_new (const char* preview, const char* record) {
	return omap_muxer_control_construct (OMAP_TYPE_MUXER_CONTROL, preview, record);
}


void omap_muxer_control_load (OmapMuxerControl* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omap_muxer_control_load_preview_bin (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


void omap_muxer_control_start_preview (OmapMuxerControl* self) {
	g_return_if_fail (self != NULL);
	omap_media_control_set_state ((OmapMediaControl*) self, GST_STATE_PLAYING);
}


void omap_muxer_control_stop_preview (OmapMuxerControl* self) {
	g_return_if_fail (self != NULL);
	omap_media_control_set_state ((OmapMediaControl*) self, GST_STATE_NULL);
	self->priv->_previewing = FALSE;
	g_signal_emit_by_name (self, "preview-stopped");
}


static gpointer _gst_object_ref0 (gpointer self) {
	return self ? gst_object_ref (self) : NULL;
}


static inline void _dynamic_set_silent0 (GstElement* obj, gboolean value) {
	g_object_set (obj, "silent", value, NULL);
}


void omap_muxer_control_start_record (OmapMuxerControl* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omap_media_control_set_state ((OmapMediaControl*) self, GST_STATE_NULL);
	omap_muxer_control_load_record_bin (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	gst_bin_add (self->preview_bin, _gst_object_ref0 ((GstElement*) self->record_bin));
	gst_element_link (self->tee, self->queue);
	if (self->overlay != NULL) {
		_dynamic_set_silent0 (self->overlay, FALSE);
	}
	omap_media_control_set_state ((OmapMediaControl*) self, GST_STATE_PLAYING);
}


void omap_muxer_control_stop_record (OmapMuxerControl* self) {
	g_return_if_fail (self != NULL);
	if (!self->priv->_recording) {
		return;
	}
	gst_element_send_event (self->videosrc, gst_event_new_eos ());
	if (self->audiosrc != NULL) {
		gst_element_send_event (self->audiosrc, gst_event_new_eos ());
	}
}


void omap_muxer_control_load_preview_bin (OmapMuxerControl* self, GError** error) {
	GError * _inner_error_;
	GstElement* _tmp0_;
	GstBin* _tmp2_;
	GstElement* _tmp1_;
	GstElement* _tmp3_;
	GstElement* _tmp4_;
	GstElement* _tmp5_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = gst_parse_launch (self->preview_desc, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->preview_bin = (_tmp2_ = (GstBin*) (_tmp1_ = _tmp0_, GST_IS_PIPELINE (_tmp1_) ? ((GstPipeline*) _tmp1_) : NULL), _gst_object_unref0 (self->preview_bin), _tmp2_);
	gst_object_set_name ((GstObject*) self->preview_bin, "preview_bin");
	omap_media_control_set_pipeline ((OmapMediaControl*) self, self->preview_bin);
	self->overlay = (_tmp3_ = gst_bin_get_by_name (self->preview_bin, "overlay"), _gst_object_unref0 (self->overlay), _tmp3_);
	self->videosrc = (_tmp4_ = gst_bin_get_by_name (self->preview_bin, "videosrc"), _gst_object_unref0 (self->videosrc), _tmp4_);
	if ((self->tee = (_tmp5_ = gst_bin_get_by_name (self->preview_bin, "tee"), _gst_object_unref0 (self->tee), _tmp5_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named tee in the preview pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
}


void omap_muxer_control_load_record_bin (OmapMuxerControl* self, GError** error) {
	GError * _inner_error_;
	GstElement* _tmp0_;
	GstBin* _tmp2_;
	GstElement* _tmp1_;
	GstElement* _tmp3_;
	GstElement* _tmp4_;
	GstElement* _tmp5_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = gst_parse_launch (self->record_desc, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->record_bin = (_tmp2_ = (GstBin*) (_tmp1_ = _tmp0_, GST_IS_PIPELINE (_tmp1_) ? ((GstPipeline*) _tmp1_) : NULL), _gst_object_unref0 (self->record_bin), _tmp2_);
	gst_object_set_name ((GstObject*) self->record_bin, "record_bin");
	if ((self->queue = (_tmp3_ = gst_bin_get_by_name (self->record_bin, "queue"), _gst_object_unref0 (self->queue), _tmp3_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named queue in the record pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
	self->audiosrc = (_tmp4_ = gst_bin_get_by_name (self->record_bin, "audiosrc"), _gst_object_unref0 (self->audiosrc), _tmp4_);
	self->filesrc = (_tmp5_ = gst_bin_get_by_name (self->record_bin, "filesrc"), _gst_object_unref0 (self->filesrc), _tmp5_);
}


void omap_muxer_control_on_state_changed (OmapMuxerControl* self, GstObject* src, GstState old, GstState current, GstState pending) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	if (src == GST_OBJECT (self->preview_bin)) {
		gboolean _tmp0_ = FALSE;
		if (old == GST_STATE_PAUSED) {
			_tmp0_ = current == GST_STATE_PLAYING;
		} else {
			_tmp0_ = FALSE;
		}
		if (_tmp0_) {
			self->priv->_previewing = TRUE;
			g_signal_emit_by_name (self, "preview-started");
		}
	} else {
		if (src == GST_OBJECT (self->record_bin)) {
			gboolean _tmp1_ = FALSE;
			if (old == GST_STATE_PAUSED) {
				_tmp1_ = current == GST_STATE_PLAYING;
			} else {
				_tmp1_ = FALSE;
			}
			if (_tmp1_) {
				self->priv->_recording = TRUE;
				g_signal_emit_by_name (self, "record-started");
			}
		}
	}
}


static inline void _dynamic_set_silent1 (GstElement* obj, gboolean value) {
	g_object_set (obj, "silent", value, NULL);
}


void omap_muxer_control_on_eos (OmapMuxerControl* self, GstObject* src) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	if (self->overlay != NULL) {
		_dynamic_set_silent1 (self->overlay, TRUE);
	}
	self->priv->_recording = FALSE;
	g_signal_emit_by_name (self, "record-stopped");
	omap_muxer_control_stop_preview (self);
	gst_element_unlink (self->tee, self->queue);
	gst_bin_remove (self->preview_bin, (GstElement*) self->record_bin);
	g_signal_emit_by_name ((OmapMediaControl*) self, "prepare-xwindow-id", ((OmapMediaControl*) self)->xoverlay);
	omap_muxer_control_start_preview (self);
}


void omap_muxer_control_stop (OmapMuxerControl* self) {
	g_return_if_fail (self != NULL);
	omap_muxer_control_stop_preview (self);
}


gboolean omap_muxer_control_get_previewing (OmapMuxerControl* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_previewing;
	return result;
}


gboolean omap_muxer_control_get_recording (OmapMuxerControl* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_recording;
	return result;
}


static void _omap_muxer_control_on_eos_omap_media_control_eos_message (OmapMuxerControl* _sender, GstObject* src, gpointer self) {
	omap_muxer_control_on_eos (self, src);
}


static void _omap_muxer_control_on_state_changed_omap_media_control_state_changed_message (OmapMuxerControl* _sender, GstObject* src, GstState old, GstState current, GstState pending, gpointer self) {
	omap_muxer_control_on_state_changed (self, src, old, current, pending);
}


static GObject * omap_muxer_control_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	OmapMuxerControl * self;
	parent_class = G_OBJECT_CLASS (omap_muxer_control_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = OMAP_MUXER_CONTROL (obj);
	{
		g_signal_connect_object ((OmapMediaControl*) self, "eos-message", (GCallback) _omap_muxer_control_on_eos_omap_media_control_eos_message, self, 0);
		g_signal_connect_object ((OmapMediaControl*) self, "state-changed-message", (GCallback) _omap_muxer_control_on_state_changed_omap_media_control_state_changed_message, self, 0);
	}
	return obj;
}


static void omap_muxer_control_class_init (OmapMuxerControlClass * klass) {
	omap_muxer_control_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (OmapMuxerControlPrivate));
	G_OBJECT_CLASS (klass)->get_property = omap_muxer_control_get_property;
	G_OBJECT_CLASS (klass)->constructor = omap_muxer_control_constructor;
	G_OBJECT_CLASS (klass)->finalize = omap_muxer_control_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OMAP_MUXER_CONTROL_PREVIEWING, g_param_spec_boolean ("previewing", "previewing", "previewing", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OMAP_MUXER_CONTROL_RECORDING, g_param_spec_boolean ("recording", "recording", "recording", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("preview_started", OMAP_TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("preview_stopped", OMAP_TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("record_started", OMAP_TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("record_stopped", OMAP_TYPE_MUXER_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void omap_muxer_control_instance_init (OmapMuxerControl * self) {
	self->priv = OMAP_MUXER_CONTROL_GET_PRIVATE (self);
}


static void omap_muxer_control_finalize (GObject* obj) {
	OmapMuxerControl * self;
	self = OMAP_MUXER_CONTROL (obj);
	{
		omap_muxer_control_stop (self);
	}
	_g_free0 (self->preview_desc);
	_g_free0 (self->record_desc);
	_gst_object_unref0 (self->overlay);
	_gst_object_unref0 (self->tee);
	_gst_object_unref0 (self->videosrc);
	_gst_object_unref0 (self->audiosrc);
	_gst_object_unref0 (self->filesrc);
	_gst_object_unref0 (self->preview_bin);
	_gst_object_unref0 (self->record_bin);
	_gst_object_unref0 (self->queue);
	G_OBJECT_CLASS (omap_muxer_control_parent_class)->finalize (obj);
}


GType omap_muxer_control_get_type (void) {
	static GType omap_muxer_control_type_id = 0;
	if (omap_muxer_control_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (OmapMuxerControlClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) omap_muxer_control_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OmapMuxerControl), 0, (GInstanceInitFunc) omap_muxer_control_instance_init, NULL };
		omap_muxer_control_type_id = g_type_register_static (OMAP_TYPE_MEDIA_CONTROL, "OmapMuxerControl", &g_define_type_info, 0);
	}
	return omap_muxer_control_type_id;
}


static void omap_muxer_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	OmapMuxerControl * self;
	self = OMAP_MUXER_CONTROL (object);
	switch (property_id) {
		case OMAP_MUXER_CONTROL_PREVIEWING:
		g_value_set_boolean (value, omap_muxer_control_get_previewing (self));
		break;
		case OMAP_MUXER_CONTROL_RECORDING:
		g_value_set_boolean (value, omap_muxer_control_get_recording (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




