/* iconlist-control.c generated by valac, the Vala compiler
 * generated from iconlist-control.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <common.h>
#include <gst/gst.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <gtk/gtk.h>
#include <gio/gio.h>


#define OMAP_TYPE_ICON_LIST_CONTROL (omap_icon_list_control_get_type ())
#define OMAP_ICON_LIST_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMAP_TYPE_ICON_LIST_CONTROL, OmapIconListControl))
#define OMAP_ICON_LIST_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMAP_TYPE_ICON_LIST_CONTROL, OmapIconListControlClass))
#define OMAP_IS_ICON_LIST_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMAP_TYPE_ICON_LIST_CONTROL))
#define OMAP_IS_ICON_LIST_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMAP_TYPE_ICON_LIST_CONTROL))
#define OMAP_ICON_LIST_CONTROL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMAP_TYPE_ICON_LIST_CONTROL, OmapIconListControlClass))

typedef struct _OmapIconListControl OmapIconListControl;
typedef struct _OmapIconListControlClass OmapIconListControlClass;
typedef struct _OmapIconListControlPrivate OmapIconListControlPrivate;

#define OMAP_ICON_LIST_CONTROL_TYPE_COL (omap_icon_list_control_col_get_type ())
#define _gst_object_unref0(var) ((var == NULL) ? NULL : (var = (gst_object_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _gtk_icon_info_free0(var) ((var == NULL) ? NULL : (var = (gtk_icon_info_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free_g_object_unref0(var) ((var == NULL) ? NULL : (var = (_g_list_free_g_object_unref (var), NULL)))
typedef struct _OmapIconListControlAddFolderData OmapIconListControlAddFolderData;
#define _gtk_tree_path_free0(var) ((var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL)))
typedef struct _OmapIconListControlFillIconsData OmapIconListControlFillIconsData;
#define _gst_caps_unref0(var) ((var == NULL) ? NULL : (var = (gst_caps_unref (var), NULL)))
#define _gst_structure_free0(var) ((var == NULL) ? NULL : (var = (gst_structure_free (var), NULL)))

struct _OmapIconListControl {
	OmapMediaControl parent_instance;
	OmapIconListControlPrivate * priv;
	GstElement* filesrc;
	GstElement* imagesink;
	GstElement* imagedec;
	GstPad* imagedec_src;
	GdkPixbuf* missing_pixbuf;
	GSourceFunc continuation;
	gpointer continuation_target;
	GDestroyNotify continuation_target_destroy_notify;
	GError* continuation_error;
};

struct _OmapIconListControlClass {
	OmapMediaControlClass parent_class;
};

struct _OmapIconListControlPrivate {
	GtkListStore* _iconlist_store;
};

typedef enum  {
	OMAP_ICON_LIST_CONTROL_COL_TEXT,
	OMAP_ICON_LIST_CONTROL_COL_FILE,
	OMAP_ICON_LIST_CONTROL_COL_PIXBUF,
	OMAP_ICON_LIST_CONTROL_COL_VALID,
	OMAP_ICON_LIST_CONTROL_COL_FILLED,
	OMAP_ICON_LIST_CONTROL_COL_WIDTH,
	OMAP_ICON_LIST_CONTROL_COL_HEIGHT
} OmapIconListControlCol;

struct _OmapIconListControlAddFolderData {
	int _state_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	OmapIconListControl* self;
	char* dirname;
	GCancellable* cancellable;
	GFile* dir;
	GFileEnumerator* file_etor;
	GList* next_files;
	GtkMessageDialog* _tmp0_;
	GError * e1;
	GError * _inner_error_;
};

struct _OmapIconListControlFillIconsData {
	int _state_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	OmapIconListControl* self;
	GtkTreePath* path;
	GtkTreePath* end;
	GCancellable* cancellable;
	gboolean _tmp0_;
	GSourceFunc _tmp1_;
	gboolean _tmp2_;
	GtkTreeIter iter;
	char* file;
	gboolean filled;
	GError* _tmp3_;
	GdkPixbuf* _tmp4_;
	gint width;
	gint height;
	GdkPixbuf* pixbuf;
	gboolean valid;
	gboolean _tmp5_;
	GdkPixbuf* _tmp7_;
	GdkPixbuf* _tmp6_;
	GdkPixbuf* _tmp8_;
};


extern GdkPixbuf* omap_icon_list_control_loading_pixbuf;
GdkPixbuf* omap_icon_list_control_loading_pixbuf = NULL;
extern GdkPixbuf* omap_icon_list_control_last_pixbuf;
GdkPixbuf* omap_icon_list_control_last_pixbuf = NULL;
extern GQuark omap_icon_list_control_pixbuf_q;
GQuark omap_icon_list_control_pixbuf_q = 0U;
extern gboolean omap_icon_list_control_pixbufs_loaded;
gboolean omap_icon_list_control_pixbufs_loaded = FALSE;
static gpointer omap_icon_list_control_parent_class = NULL;

#define ICON_PIPELINE_DESC "filesrc name=filesrc ! jpegdec name=imagedec ! ffmpegcolorspace ! vide" \
"oscale !\n" \
"video/x-raw-rgb,width=128,height=96 ! gdkpixbufsink name=imagesink"
#define IMAGE_FILE_ATTRIBUTES "standard::name,standard::display-name,standard::content-type"
GType omap_icon_list_control_get_type (void) G_GNUC_CONST;
#define OMAP_ICON_LIST_CONTROL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), OMAP_TYPE_ICON_LIST_CONTROL, OmapIconListControlPrivate))
enum  {
	OMAP_ICON_LIST_CONTROL_DUMMY_PROPERTY,
	OMAP_ICON_LIST_CONTROL_ICONLIST_STORE
};
GType omap_icon_list_control_col_get_type (void) G_GNUC_CONST;
void omap_icon_list_control_set_iconlist_store (OmapIconListControl* self, GtkListStore* value);
void omap_icon_list_control_setup_icons (OmapIconListControl* self, GError** error);
void omap_icon_list_control_setup_elements (OmapIconListControl* self, GError** error);
OmapIconListControl* omap_icon_list_control_new (GtkListStore* model, GError** error);
OmapIconListControl* omap_icon_list_control_construct (GType object_type, GtkListStore* model, GError** error);
void omap_icon_list_control_setup_pipeline (OmapIconListControl* self, GError** error);
static void omap_icon_list_control_add_folder_data_free (gpointer _data);
static void omap_icon_list_control_add_folder_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _g_list_free_g_object_unref (GList* self);
void omap_icon_list_control_add_next_files (OmapIconListControl* self, const char* dirname, GList* files);
void omap_icon_list_control_add_folder (OmapIconListControl* self, const char* dirname, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
void omap_icon_list_control_add_folder_finish (OmapIconListControl* self, GAsyncResult* _res_);
static gboolean omap_icon_list_control_add_folder_co (OmapIconListControlAddFolderData* data);
GtkListStore* omap_icon_list_control_get_iconlist_store (OmapIconListControl* self);
static void omap_icon_list_control_fill_icons_data_free (gpointer _data);
static void omap_icon_list_control_fill_icons_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
void omap_icon_list_control_fill_icons (OmapIconListControl* self, GtkTreePath* path, GtkTreePath* end, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
void omap_icon_list_control_fill_icons_finish (OmapIconListControl* self, GAsyncResult* _res_);
static gboolean _omap_icon_list_control_fill_icons_co_gsource_func (gpointer self);
static inline void _dynamic_set_location0 (GstElement* obj, const char* value);
void omap_icon_list_control_get_playing_image_size (OmapIconListControl* self, gint* width, gint* height);
static gboolean omap_icon_list_control_fill_icons_co (OmapIconListControlFillIconsData* data);
static inline GdkPixbuf* _dynamic_get_last_pixbuf1 (GstElement* obj);
void omap_icon_list_control_on_element (OmapIconListControl* self, GstObject* src, const GstStructure* structure);
void omap_icon_list_control_on_error (OmapIconListControl* self, GstObject* src, GError* _error_, const char* debug);
void omap_icon_list_control_on_eos (OmapIconListControl* self, GstObject* src);
OmapIconListControlCol omap_icon_list_control_get_text_column (void);
OmapIconListControlCol omap_icon_list_control_get_pixbuf_column (void);
gboolean omap_icon_list_control_iter_is_valid (OmapIconListControl* self, GtkTreeIter* iter);
gboolean omap_icon_list_control_iter_is_filled (OmapIconListControl* self, GtkTreeIter* iter);
char* omap_icon_list_control_iter_get_file (OmapIconListControl* self, GtkTreeIter* iter);
void omap_icon_list_control_iter_get_size (OmapIconListControl* self, GtkTreeIter* iter, gint* width, gint* height);
GtkListStore* omap_icon_list_control_model_new (void);
static void _omap_icon_list_control_on_eos_omap_media_control_eos_message (OmapMediaControl* _sender, GstObject* src, gpointer self);
static void _omap_icon_list_control_on_error_omap_media_control_error_message (OmapMediaControl* _sender, GstObject* src, GError* _error_, const char* debug, gpointer self);
static void _omap_icon_list_control_on_element_omap_media_control_element_message (OmapMediaControl* _sender, GstObject* src, const GstStructure* structure, gpointer self);
static GObject * omap_icon_list_control_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void omap_icon_list_control_finalize (GObject* obj);
static void omap_icon_list_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void omap_icon_list_control_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static int _vala_strcmp0 (const char * str1, const char * str2);



GType omap_icon_list_control_col_get_type (void) {
	static volatile gsize omap_icon_list_control_col_type_id__volatile = 0;
	if (g_once_init_enter (&omap_icon_list_control_col_type_id__volatile)) {
		static const GEnumValue values[] = {{OMAP_ICON_LIST_CONTROL_COL_TEXT, "OMAP_ICON_LIST_CONTROL_COL_TEXT", "text"}, {OMAP_ICON_LIST_CONTROL_COL_FILE, "OMAP_ICON_LIST_CONTROL_COL_FILE", "file"}, {OMAP_ICON_LIST_CONTROL_COL_PIXBUF, "OMAP_ICON_LIST_CONTROL_COL_PIXBUF", "pixbuf"}, {OMAP_ICON_LIST_CONTROL_COL_VALID, "OMAP_ICON_LIST_CONTROL_COL_VALID", "valid"}, {OMAP_ICON_LIST_CONTROL_COL_FILLED, "OMAP_ICON_LIST_CONTROL_COL_FILLED", "filled"}, {OMAP_ICON_LIST_CONTROL_COL_WIDTH, "OMAP_ICON_LIST_CONTROL_COL_WIDTH", "width"}, {OMAP_ICON_LIST_CONTROL_COL_HEIGHT, "OMAP_ICON_LIST_CONTROL_COL_HEIGHT", "height"}, {0, NULL, NULL}};
		GType omap_icon_list_control_col_type_id;
		omap_icon_list_control_col_type_id = g_enum_register_static ("OmapIconListControlCol", values);
		g_once_init_leave (&omap_icon_list_control_col_type_id__volatile, omap_icon_list_control_col_type_id);
	}
	return omap_icon_list_control_col_type_id__volatile;
}


OmapIconListControl* omap_icon_list_control_construct (GType object_type, GtkListStore* model, GError** error) {
	GError * _inner_error_;
	OmapIconListControl * self;
	g_return_val_if_fail (model != NULL, NULL);
	_inner_error_ = NULL;
	self = g_object_newv (object_type, 0, NULL);
	omap_icon_list_control_set_iconlist_store (self, model);
	if (!omap_icon_list_control_pixbufs_loaded) {
		omap_icon_list_control_setup_icons (self, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (self);
			return NULL;
		}
		omap_icon_list_control_pixbufs_loaded = TRUE;
	}
	omap_icon_list_control_setup_elements (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (self);
		return NULL;
	}
	return self;
}


OmapIconListControl* omap_icon_list_control_new (GtkListStore* model, GError** error) {
	return omap_icon_list_control_construct (OMAP_TYPE_ICON_LIST_CONTROL, model, error);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void omap_icon_list_control_setup_icons (OmapIconListControl* self, GError** error) {
	GError * _inner_error_;
	GtkIconTheme* icon_theme;
	GtkIconInfo* icon_info;
	GtkIconInfo* _tmp0_;
	GtkIconInfo* _tmp3_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	icon_theme = _g_object_ref0 (gtk_icon_theme_get_default ());
	icon_info = NULL;
	icon_info = (_tmp0_ = gtk_icon_theme_lookup_icon (icon_theme, GTK_STOCK_MISSING_IMAGE, 96, GTK_ICON_LOOKUP_FORCE_SIZE), _gtk_icon_info_free0 (icon_info), _tmp0_);
	if (icon_info != NULL) {
		GdkPixbuf* _tmp1_;
		GdkPixbuf* _tmp2_;
		_tmp1_ = gtk_icon_info_load_icon (icon_info, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_gtk_icon_info_free0 (icon_info);
			_g_object_unref0 (icon_theme);
			return;
		}
		self->missing_pixbuf = (_tmp2_ = _tmp1_, _g_object_unref0 (self->missing_pixbuf), _tmp2_);
	}
	icon_info = (_tmp3_ = gtk_icon_theme_lookup_icon (icon_theme, "image-loading", 96, GTK_ICON_LOOKUP_FORCE_SIZE), _gtk_icon_info_free0 (icon_info), _tmp3_);
	if (icon_info != NULL) {
		GdkPixbuf* _tmp4_;
		GdkPixbuf* _tmp5_;
		_tmp4_ = gtk_icon_info_load_icon (icon_info, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_gtk_icon_info_free0 (icon_info);
			_g_object_unref0 (icon_theme);
			return;
		}
		omap_icon_list_control_loading_pixbuf = (_tmp5_ = _tmp4_, _g_object_unref0 (omap_icon_list_control_loading_pixbuf), _tmp5_);
	}
	_gtk_icon_info_free0 (icon_info);
	_g_object_unref0 (icon_theme);
}


void omap_icon_list_control_setup_elements (OmapIconListControl* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omap_icon_list_control_setup_pipeline (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


void omap_icon_list_control_setup_pipeline (OmapIconListControl* self, GError** error) {
	GError * _inner_error_;
	GstElement* _tmp0_;
	GstElement* _tmp1_;
	GstPipeline* icon_pipeline;
	GstElement* _tmp2_;
	GstElement* _tmp3_;
	GstElement* _tmp4_;
	GstPad* _tmp5_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = gst_parse_launch (ICON_PIPELINE_DESC, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	icon_pipeline = (_tmp1_ = _tmp0_, GST_IS_PIPELINE (_tmp1_) ? ((GstPipeline*) _tmp1_) : NULL);
	gst_object_set_name ((GstObject*) icon_pipeline, "icon_pipeline");
	if ((self->filesrc = (_tmp2_ = gst_bin_get_by_name ((GstBin*) icon_pipeline, "filesrc"), _gst_object_unref0 (self->filesrc), _tmp2_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named filesrc in the icon_pipeline");
		{
			g_propagate_error (error, _inner_error_);
			_gst_object_unref0 (icon_pipeline);
			return;
		}
	}
	if ((self->imagesink = (_tmp3_ = gst_bin_get_by_name ((GstBin*) icon_pipeline, "imagesink"), _gst_object_unref0 (self->imagesink), _tmp3_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named imagesink in the icon_pipeline");
		{
			g_propagate_error (error, _inner_error_);
			_gst_object_unref0 (icon_pipeline);
			return;
		}
	}
	if ((self->imagedec = (_tmp4_ = gst_bin_get_by_name ((GstBin*) icon_pipeline, "imagedec"), _gst_object_unref0 (self->imagedec), _tmp4_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named imagedec in the icon_pipeline");
		{
			g_propagate_error (error, _inner_error_);
			_gst_object_unref0 (icon_pipeline);
			return;
		}
	}
	self->imagedec_src = (_tmp5_ = gst_element_get_static_pad (self->imagedec, "src"), _gst_object_unref0 (self->imagedec_src), _tmp5_);
	omap_media_control_set_pipeline ((OmapMediaControl*) self, (GstBin*) icon_pipeline);
	_gst_object_unref0 (icon_pipeline);
}


static void omap_icon_list_control_add_folder_data_free (gpointer _data) {
	OmapIconListControlAddFolderData* data;
	data = _data;
	_g_free0 (data->dirname);
	_g_object_unref0 (data->cancellable);
	g_object_unref (data->self);
	g_slice_free (OmapIconListControlAddFolderData, data);
}


void omap_icon_list_control_add_folder (OmapIconListControl* self, const char* dirname, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	OmapIconListControlAddFolderData* _data_;
	_data_ = g_slice_new0 (OmapIconListControlAddFolderData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, omap_icon_list_control_add_folder);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, omap_icon_list_control_add_folder_data_free);
	_data_->self = g_object_ref (self);
	_data_->dirname = g_strdup (dirname);
	_data_->cancellable = _g_object_ref0 (cancellable);
	omap_icon_list_control_add_folder_co (_data_);
}


void omap_icon_list_control_add_folder_finish (OmapIconListControl* self, GAsyncResult* _res_) {
	OmapIconListControlAddFolderData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void omap_icon_list_control_add_folder_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	OmapIconListControlAddFolderData* data;
	data = _user_data_;
	data->_res_ = _res_;
	omap_icon_list_control_add_folder_co (data);
}


static void _g_list_free_g_object_unref (GList* self) {
	g_list_foreach (self, (GFunc) g_object_unref, NULL);
	g_list_free (self);
}


static gboolean omap_icon_list_control_add_folder_co (OmapIconListControlAddFolderData* data) {
	switch (data->_state_) {
		case 0:
		goto _state_0;
		case 2:
		goto _state_2;
		case 3:
		goto _state_3;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	{
		data->dir = g_file_new_for_path (data->dirname);
		{
			data->_state_ = 2;
			g_file_enumerate_children_async (data->dir, IMAGE_FILE_ATTRIBUTES, G_FILE_QUERY_INFO_NONE, G_PRIORITY_DEFAULT, data->cancellable, omap_icon_list_control_add_folder_ready, data);
			return FALSE;
			_state_2:
			data->file_etor = g_file_enumerate_children_finish (data->dir, data->_res_, &data->_inner_error_);
			if (data->_inner_error_ != NULL) {
				goto __catch1_g_error;
			}
			while (TRUE) {
				if (!(!g_cancellable_is_cancelled (data->cancellable))) {
					break;
				}
				data->_state_ = 3;
				g_file_enumerator_next_files_async (data->file_etor, 5, G_PRIORITY_DEFAULT, data->cancellable, omap_icon_list_control_add_folder_ready, data);
				return FALSE;
				_state_3:
				data->next_files = g_file_enumerator_next_files_finish (data->file_etor, data->_res_, &data->_inner_error_);
				if (data->_inner_error_ != NULL) {
					_g_object_unref0 (data->file_etor);
					goto __catch1_g_error;
				}
				if (data->next_files == NULL) {
					__g_list_free_g_object_unref0 (data->next_files);
					break;
				}
				omap_icon_list_control_add_next_files (data->self, data->dirname, data->next_files);
				__g_list_free_g_object_unref0 (data->next_files);
			}
			_g_object_unref0 (data->file_etor);
		}
		goto __finally1;
		__catch1_g_error:
		{
			data->e1 = data->_inner_error_;
			data->_inner_error_ = NULL;
			{
				data->_tmp0_ = omap_error_dialog (data->e1);
				_g_object_unref0 (data->_tmp0_);
				_g_error_free0 (data->e1);
			}
		}
		__finally1:
		{
			g_signal_emit_by_name (data->self, "files-added");
		}
		if (data->_inner_error_ != NULL) {
			_g_object_unref0 (data->dir);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, data->_inner_error_->message, g_quark_to_string (data->_inner_error_->domain), data->_inner_error_->code);
			g_clear_error (&data->_inner_error_);
			return FALSE;
		}
		_g_object_unref0 (data->dir);
	}
	{
		if (data->_state_ == 0) {
			g_simple_async_result_complete_in_idle (data->_async_result);
		} else {
			g_simple_async_result_complete (data->_async_result);
		}
		g_object_unref (data->_async_result);
		return FALSE;
	}
}


void omap_icon_list_control_add_next_files (OmapIconListControl* self, const char* dirname, GList* files) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (dirname != NULL);
	{
		GList* info_collection;
		GList* info_it;
		info_collection = files;
		for (info_it = info_collection; info_it != NULL; info_it = info_it->next) {
			GFileInfo* info;
			info = _g_object_ref0 ((GFileInfo*) info_it->data);
			{
				if (_vala_strcmp0 (g_file_info_get_content_type (info), "image/jpeg") == 0) {
					char* file;
					char* text;
					file = g_build_filename (dirname, g_file_info_get_name (info), NULL);
					text = g_strdup (g_file_info_get_display_name (info));
					gtk_list_store_insert_with_values (self->priv->_iconlist_store, NULL, -1, OMAP_ICON_LIST_CONTROL_COL_TEXT, text, OMAP_ICON_LIST_CONTROL_COL_FILE, file, OMAP_ICON_LIST_CONTROL_COL_PIXBUF, omap_icon_list_control_loading_pixbuf, -1, -1);
					_g_free0 (text);
					_g_free0 (file);
				}
				_g_object_unref0 (info);
			}
		}
	}
}


static void omap_icon_list_control_fill_icons_data_free (gpointer _data) {
	OmapIconListControlFillIconsData* data;
	data = _data;
	_gtk_tree_path_free0 (data->path);
	_gtk_tree_path_free0 (data->end);
	_g_object_unref0 (data->cancellable);
	g_object_unref (data->self);
	g_slice_free (OmapIconListControlFillIconsData, data);
}


static gpointer _gtk_tree_path_copy0 (gpointer self) {
	return self ? gtk_tree_path_copy (self) : NULL;
}


void omap_icon_list_control_fill_icons (OmapIconListControl* self, GtkTreePath* path, GtkTreePath* end, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	OmapIconListControlFillIconsData* _data_;
	_data_ = g_slice_new0 (OmapIconListControlFillIconsData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, omap_icon_list_control_fill_icons);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, omap_icon_list_control_fill_icons_data_free);
	_data_->self = g_object_ref (self);
	_data_->path = _gtk_tree_path_copy0 (path);
	_data_->end = _gtk_tree_path_copy0 (end);
	_data_->cancellable = _g_object_ref0 (cancellable);
	omap_icon_list_control_fill_icons_co (_data_);
}


void omap_icon_list_control_fill_icons_finish (OmapIconListControl* self, GAsyncResult* _res_) {
	OmapIconListControlFillIconsData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void omap_icon_list_control_fill_icons_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	OmapIconListControlFillIconsData* data;
	data = _user_data_;
	data->_res_ = _res_;
	omap_icon_list_control_fill_icons_co (data);
}


static gboolean _omap_icon_list_control_fill_icons_co_gsource_func (gpointer self) {
	gboolean result;
	result = omap_icon_list_control_fill_icons_co (self);
	return result;
}


static inline void _dynamic_set_location0 (GstElement* obj, const char* value) {
	g_object_set (obj, "location", value, NULL);
}


static gboolean omap_icon_list_control_fill_icons_co (OmapIconListControlFillIconsData* data) {
	switch (data->_state_) {
		case 0:
		goto _state_0;
		case 4:
		goto _state_4;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	{
		if (data->path != NULL) {
			data->_tmp0_ = data->end != NULL;
		} else {
			data->_tmp0_ = FALSE;
		}
		if (data->_tmp0_) {
			data->self->continuation = (data->_tmp1_ = _omap_icon_list_control_fill_icons_co_gsource_func, ((data->self->continuation_target_destroy_notify == NULL) ? NULL : (data->self->continuation_target_destroy_notify (data->self->continuation_target), NULL), data->self->continuation = NULL, data->self->continuation_target = NULL, data->self->continuation_target_destroy_notify = NULL), data->self->continuation_target = data, data->self->continuation_target_destroy_notify = NULL, data->_tmp1_);
			omap_media_control_set_state ((OmapMediaControl*) data->self, GST_STATE_READY);
			while (TRUE) {
				if (gtk_tree_path_compare (data->path, data->end) > 0) {
					data->_tmp2_ = TRUE;
				} else {
					data->_tmp2_ = g_cancellable_is_cancelled (data->cancellable);
				}
				if (!(!data->_tmp2_)) {
					break;
				}
				gtk_tree_model_get_iter ((GtkTreeModel*) data->self->priv->_iconlist_store, &data->iter, data->path);
				gtk_tree_model_get ((GtkTreeModel*) data->self->priv->_iconlist_store, &data->iter, OMAP_ICON_LIST_CONTROL_COL_FILE, &data->file, OMAP_ICON_LIST_CONTROL_COL_FILLED, &data->filled, -1, -1);
				if (!data->filled) {
					data->self->continuation_error = (data->_tmp3_ = NULL, _g_error_free0 (data->self->continuation_error), data->_tmp3_);
					omap_icon_list_control_last_pixbuf = (data->_tmp4_ = NULL, _g_object_unref0 (omap_icon_list_control_last_pixbuf), data->_tmp4_);
					_dynamic_set_location0 (data->self->filesrc, data->file);
					omap_media_control_set_state ((OmapMediaControl*) data->self, GST_STATE_PLAYING);
					data->_state_ = 4;
					return FALSE;
					_state_4:
					;
					data->width = 0;
					data->height = 0;
					if (data->self->continuation_error == NULL) {
						data->_tmp5_ = omap_icon_list_control_last_pixbuf != NULL;
					} else {
						data->_tmp5_ = FALSE;
					}
					data->valid = data->_tmp5_;
					if (data->valid) {
						data->pixbuf = (data->_tmp7_ = (data->_tmp6_ = omap_icon_list_control_last_pixbuf, omap_icon_list_control_last_pixbuf = NULL, data->_tmp6_), _g_object_unref0 (data->pixbuf), data->_tmp7_);
						omap_icon_list_control_get_playing_image_size (data->self, &data->width, &data->height);
					} else {
						data->pixbuf = (data->_tmp8_ = _g_object_ref0 (data->self->missing_pixbuf), _g_object_unref0 (data->pixbuf), data->_tmp8_);
					}
					gtk_list_store_set (data->self->priv->_iconlist_store, &data->iter, OMAP_ICON_LIST_CONTROL_COL_PIXBUF, data->pixbuf, OMAP_ICON_LIST_CONTROL_COL_VALID, data->valid, OMAP_ICON_LIST_CONTROL_COL_FILLED, TRUE, OMAP_ICON_LIST_CONTROL_COL_WIDTH, data->width, OMAP_ICON_LIST_CONTROL_COL_HEIGHT, data->height, -1, -1);
					_g_object_unref0 (data->pixbuf);
				}
				omap_media_control_set_state ((OmapMediaControl*) data->self, GST_STATE_READY);
				gtk_tree_path_next (data->path);
				_g_free0 (data->file);
			}
			omap_media_control_set_state ((OmapMediaControl*) data->self, GST_STATE_NULL);
		}
		g_signal_emit_by_name (data->self, "icons-filled");
	}
	{
		if (data->_state_ == 0) {
			g_simple_async_result_complete_in_idle (data->_async_result);
		} else {
			g_simple_async_result_complete (data->_async_result);
		}
		g_object_unref (data->_async_result);
		return FALSE;
	}
}


static gpointer _gst_structure_copy0 (gpointer self) {
	return self ? gst_structure_copy (self) : NULL;
}


void omap_icon_list_control_get_playing_image_size (OmapIconListControl* self, gint* width, gint* height) {
	GstCaps* _tmp0_;
	GstStructure* _tmp1_;
	GstStructure* st;
	g_return_if_fail (self != NULL);
	st = (_tmp1_ = _gst_structure_copy0 (gst_caps_get_structure (_tmp0_ = gst_pad_get_negotiated_caps (self->imagedec_src), (guint) 0)), _gst_caps_unref0 (_tmp0_), _tmp1_);
	gst_structure_get_int (st, "width", width);
	gst_structure_get_int (st, "height", height);
	_gst_structure_free0 (st);
}


static inline GdkPixbuf* _dynamic_get_last_pixbuf1 (GstElement* obj) {
	GdkPixbuf* result;
	g_object_get (obj, "last-pixbuf", &result, NULL);
	return result;
}


void omap_icon_list_control_on_element (OmapIconListControl* self, GstObject* src, const GstStructure* structure) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	g_return_if_fail (structure != NULL);
	if (src == GST_OBJECT (self->imagesink)) {
		_tmp0_ = gst_structure_get_name_id (structure) == omap_icon_list_control_pixbuf_q;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GdkPixbuf* _tmp1_;
		omap_icon_list_control_last_pixbuf = (_tmp1_ = _dynamic_get_last_pixbuf1 (self->imagesink), _g_object_unref0 (omap_icon_list_control_last_pixbuf), _tmp1_);
	}
}


static gpointer _g_error_copy0 (gpointer self) {
	return self ? g_error_copy (self) : NULL;
}


void omap_icon_list_control_on_error (OmapIconListControl* self, GstObject* src, GError* _error_, const char* debug) {
	GError* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	g_return_if_fail (debug != NULL);
	self->continuation_error = (_tmp0_ = _g_error_copy0 (_error_), _g_error_free0 (self->continuation_error), _tmp0_);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, self->continuation, self->continuation_target, NULL);
}


void omap_icon_list_control_on_eos (OmapIconListControl* self, GstObject* src) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (src != NULL);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, self->continuation, self->continuation_target, NULL);
}


OmapIconListControlCol omap_icon_list_control_get_text_column (void) {
	OmapIconListControlCol result = 0;
	result = OMAP_ICON_LIST_CONTROL_COL_TEXT;
	return result;
}


OmapIconListControlCol omap_icon_list_control_get_pixbuf_column (void) {
	OmapIconListControlCol result = 0;
	result = OMAP_ICON_LIST_CONTROL_COL_PIXBUF;
	return result;
}


gboolean omap_icon_list_control_iter_is_valid (OmapIconListControl* self, GtkTreeIter* iter) {
	gboolean result = FALSE;
	gboolean valid = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	gtk_tree_model_get ((GtkTreeModel*) self->priv->_iconlist_store, iter, OMAP_ICON_LIST_CONTROL_COL_VALID, &valid, -1, -1);
	result = valid;
	return result;
}


gboolean omap_icon_list_control_iter_is_filled (OmapIconListControl* self, GtkTreeIter* iter) {
	gboolean result = FALSE;
	gboolean filled = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	gtk_tree_model_get ((GtkTreeModel*) self->priv->_iconlist_store, iter, OMAP_ICON_LIST_CONTROL_COL_FILLED, &filled, -1, -1);
	result = filled;
	return result;
}


char* omap_icon_list_control_iter_get_file (OmapIconListControl* self, GtkTreeIter* iter) {
	char* result = NULL;
	char* file;
	g_return_val_if_fail (self != NULL, NULL);
	file = NULL;
	gtk_tree_model_get ((GtkTreeModel*) self->priv->_iconlist_store, iter, OMAP_ICON_LIST_CONTROL_COL_FILE, &file, -1, -1);
	result = file;
	return result;
}


void omap_icon_list_control_iter_get_size (OmapIconListControl* self, GtkTreeIter* iter, gint* width, gint* height) {
	g_return_if_fail (self != NULL);
	gtk_tree_model_get ((GtkTreeModel*) self->priv->_iconlist_store, iter, OMAP_ICON_LIST_CONTROL_COL_WIDTH, width, OMAP_ICON_LIST_CONTROL_COL_HEIGHT, height, -1, -1);
}


GtkListStore* omap_icon_list_control_model_new (void) {
	GtkListStore* result = NULL;
	GType s;
	GType p;
	GType b;
	GType i;
	s = G_TYPE_STRING;
	p = GDK_TYPE_PIXBUF;
	b = G_TYPE_BOOLEAN;
	i = G_TYPE_INT;
	result = gtk_list_store_new (7, s, s, p, b, b, i, i, NULL);
	return result;
}


GtkListStore* omap_icon_list_control_get_iconlist_store (OmapIconListControl* self) {
	GtkListStore* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_iconlist_store;
	return result;
}


void omap_icon_list_control_set_iconlist_store (OmapIconListControl* self, GtkListStore* value) {
	g_return_if_fail (self != NULL);
	self->priv->_iconlist_store = value;
	g_object_notify ((GObject *) self, "iconlist-store");
}


static void _omap_icon_list_control_on_eos_omap_media_control_eos_message (OmapMediaControl* _sender, GstObject* src, gpointer self) {
	omap_icon_list_control_on_eos (self, src);
}


static void _omap_icon_list_control_on_error_omap_media_control_error_message (OmapMediaControl* _sender, GstObject* src, GError* _error_, const char* debug, gpointer self) {
	omap_icon_list_control_on_error (self, src, _error_, debug);
}


static void _omap_icon_list_control_on_element_omap_media_control_element_message (OmapMediaControl* _sender, GstObject* src, const GstStructure* structure, gpointer self) {
	omap_icon_list_control_on_element (self, src, structure);
}


static GObject * omap_icon_list_control_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	OmapIconListControl * self;
	parent_class = G_OBJECT_CLASS (omap_icon_list_control_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = OMAP_ICON_LIST_CONTROL (obj);
	{
		g_signal_connect_object ((OmapMediaControl*) self, "eos-message", (GCallback) _omap_icon_list_control_on_eos_omap_media_control_eos_message, self, 0);
		g_signal_connect_object ((OmapMediaControl*) self, "error-message", (GCallback) _omap_icon_list_control_on_error_omap_media_control_error_message, self, 0);
		g_signal_connect_object ((OmapMediaControl*) self, "element-message", (GCallback) _omap_icon_list_control_on_element_omap_media_control_element_message, self, 0);
	}
	return obj;
}


static void omap_icon_list_control_class_init (OmapIconListControlClass * klass) {
	omap_icon_list_control_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (OmapIconListControlPrivate));
	G_OBJECT_CLASS (klass)->get_property = omap_icon_list_control_get_property;
	G_OBJECT_CLASS (klass)->set_property = omap_icon_list_control_set_property;
	G_OBJECT_CLASS (klass)->constructor = omap_icon_list_control_constructor;
	G_OBJECT_CLASS (klass)->finalize = omap_icon_list_control_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OMAP_ICON_LIST_CONTROL_ICONLIST_STORE, g_param_spec_object ("iconlist-store", "iconlist-store", "iconlist-store", GTK_TYPE_LIST_STORE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("files_added", OMAP_TYPE_ICON_LIST_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("icons_filled", OMAP_TYPE_ICON_LIST_CONTROL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	omap_icon_list_control_pixbuf_q = g_quark_from_string ("pixbuf");
}


static void omap_icon_list_control_instance_init (OmapIconListControl * self) {
	self->priv = OMAP_ICON_LIST_CONTROL_GET_PRIVATE (self);
}


static void omap_icon_list_control_finalize (GObject* obj) {
	OmapIconListControl * self;
	self = OMAP_ICON_LIST_CONTROL (obj);
	_gst_object_unref0 (self->filesrc);
	_gst_object_unref0 (self->imagesink);
	_gst_object_unref0 (self->imagedec);
	_gst_object_unref0 (self->imagedec_src);
	_g_object_unref0 (self->missing_pixbuf);
	(self->continuation_target_destroy_notify == NULL) ? NULL : (self->continuation_target_destroy_notify (self->continuation_target), NULL);
	self->continuation = NULL;
	self->continuation_target = NULL;
	self->continuation_target_destroy_notify = NULL;
	_g_error_free0 (self->continuation_error);
	G_OBJECT_CLASS (omap_icon_list_control_parent_class)->finalize (obj);
}


GType omap_icon_list_control_get_type (void) {
	static volatile gsize omap_icon_list_control_type_id__volatile = 0;
	if (g_once_init_enter (&omap_icon_list_control_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (OmapIconListControlClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) omap_icon_list_control_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OmapIconListControl), 0, (GInstanceInitFunc) omap_icon_list_control_instance_init, NULL };
		GType omap_icon_list_control_type_id;
		omap_icon_list_control_type_id = g_type_register_static (OMAP_TYPE_MEDIA_CONTROL, "OmapIconListControl", &g_define_type_info, 0);
		g_once_init_leave (&omap_icon_list_control_type_id__volatile, omap_icon_list_control_type_id);
	}
	return omap_icon_list_control_type_id__volatile;
}


static void omap_icon_list_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	OmapIconListControl * self;
	self = OMAP_ICON_LIST_CONTROL (object);
	switch (property_id) {
		case OMAP_ICON_LIST_CONTROL_ICONLIST_STORE:
		g_value_set_object (value, omap_icon_list_control_get_iconlist_store (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void omap_icon_list_control_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	OmapIconListControl * self;
	self = OMAP_ICON_LIST_CONTROL (object);
	switch (property_id) {
		case OMAP_ICON_LIST_CONTROL_ICONLIST_STORE:
		omap_icon_list_control_set_iconlist_store (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




