/* icon-list-control.c generated by valac, the Vala compiler
 * generated from icon-list-control.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gst/gst.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_ICON_LIST_CONTROL (icon_list_control_get_type ())
#define ICON_LIST_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ICON_LIST_CONTROL, IconListControl))
#define ICON_LIST_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ICON_LIST_CONTROL, IconListControlClass))
#define IS_ICON_LIST_CONTROL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ICON_LIST_CONTROL))
#define IS_ICON_LIST_CONTROL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ICON_LIST_CONTROL))
#define ICON_LIST_CONTROL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ICON_LIST_CONTROL, IconListControlClass))

typedef struct _IconListControl IconListControl;
typedef struct _IconListControlClass IconListControlClass;
typedef struct _IconListControlPrivate IconListControlPrivate;
#define _gst_object_unref0(var) ((var == NULL) ? NULL : (var = (gst_object_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _gtk_icon_info_free0(var) ((var == NULL) ? NULL : (var = (gtk_icon_info_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free_g_object_unref0(var) ((var == NULL) ? NULL : (var = (_g_list_free_g_object_unref (var), NULL)))
typedef struct _IconListControlAddFolderData IconListControlAddFolderData;

#define TYPE_IMAGE_LIST_COL (image_list_col_get_type ())
typedef struct _IconListControlRetrieveIconsData IconListControlRetrieveIconsData;
#define _gst_structure_free0(var) ((var == NULL) ? NULL : (var = (gst_structure_free (var), NULL)))

struct _IconListControl {
	GObject parent_instance;
	IconListControlPrivate * priv;
	GstPipeline* pipeline;
	GstElement* filesrc;
	GstElement* imagesink;
	GdkPixbuf* missing_pixbuf;
	GSourceFunc continuation;
	gpointer continuation_target;
	GDestroyNotify continuation_target_destroy_notify;
	GError* continuation_error;
};

struct _IconListControlClass {
	GObjectClass parent_class;
};

struct _IconListControlPrivate {
	GtkListStore* _iconlist_store;
};

struct _IconListControlAddFolderData {
	int _state_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	IconListControl* self;
	char* dirname;
	GFile* dir;
	GFileEnumerator* file_etor;
	GList* files;
	char* _tmp0_;
	GError * e1;
	GError * _inner_error_;
};

typedef enum  {
	IMAGE_LIST_COL_TEXT,
	IMAGE_LIST_COL_FILE,
	IMAGE_LIST_COL_PIXBUF
} ImageListCol;

struct _IconListControlRetrieveIconsData {
	int _state_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	IconListControl* self;
	GtkTreeIter iter;
	GSourceFunc _tmp0_;
	gboolean _tmp1_;
	char* file;
	char* display;
	GdkPixbuf* _tmp2_;
	GError* _tmp3_;
	GdkPixbuf* pixbuf;
	gboolean _tmp4_;
	GdkPixbuf* _tmp5_;
	GdkPixbuf* _tmp6_;
};


extern GdkPixbuf* icon_list_control_loading_pixbuf;
GdkPixbuf* icon_list_control_loading_pixbuf = NULL;
extern GdkPixbuf* icon_list_control_last_pixbuf;
GdkPixbuf* icon_list_control_last_pixbuf = NULL;
extern GQuark icon_list_control_pixbuf_q;
GQuark icon_list_control_pixbuf_q = 0U;
extern gboolean icon_list_control_pixbufs_loaded;
gboolean icon_list_control_pixbufs_loaded = FALSE;
static gpointer icon_list_control_parent_class = NULL;

#define PIXBUF_PIPELINE_DESC "\nfilesrc name=filesrc ! jpegdec ! ffmpegcolorspace ! videoscale !\nvideo/x-raw-rgb,width=128,height=96 ! gdkpixbufsink name=imagesink\n"
#define IMAGE_FILE_ATTRIBUTES "standard::name,standard::display-name,standard::content-type"
GType icon_list_control_get_type (void);
#define ICON_LIST_CONTROL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ICON_LIST_CONTROL, IconListControlPrivate))
enum  {
	ICON_LIST_CONTROL_DUMMY_PROPERTY,
	ICON_LIST_CONTROL_ICONLIST_STORE
};
void icon_list_control_set_iconlist_store (IconListControl* self, GtkListStore* value);
void icon_list_control_setup_icons (IconListControl* self, GError** error);
void icon_list_control_setup_elements (IconListControl* self, GError** error);
IconListControl* icon_list_control_new (GtkListStore* model, GError** error);
IconListControl* icon_list_control_construct (GType object_type, GtkListStore* model, GError** error);
void icon_list_control_on_bus_message (IconListControl* self, GstMessage* message);
static void _icon_list_control_on_bus_message_gst_bus_message (GstBus* _sender, GstMessage* message, gpointer self);
static void icon_list_control_add_folder_data_free (gpointer _data);
static void icon_list_control_add_folder_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _g_list_free_g_object_unref (GList* self);
void icon_list_control_add_next_files (IconListControl* self, const char* dirname, GList* files);
void icon_list_control_retrieve_icons (IconListControl* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void icon_list_control_retrieve_icons_finish (IconListControl* self, GAsyncResult* _res_);
void icon_list_control_add_folder (IconListControl* self, const char* dirname, GAsyncReadyCallback _callback_, gpointer _user_data_);
void icon_list_control_add_folder_finish (IconListControl* self, GAsyncResult* _res_);
static gboolean icon_list_control_add_folder_co (IconListControlAddFolderData* data);
GtkListStore* icon_list_control_get_iconlist_store (IconListControl* self);
GType image_list_col_get_type (void);
static void icon_list_control_retrieve_icons_data_free (gpointer _data);
static void icon_list_control_retrieve_icons_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static gboolean _icon_list_control_retrieve_icons_co_gsource_func (gpointer self);
static inline void _dynamic_set_location0 (GstElement* obj, const char* value);
static gboolean icon_list_control_retrieve_icons_co (IconListControlRetrieveIconsData* data);
static inline GdkPixbuf* _dynamic_get_last_pixbuf1 (GstElement* obj);
static void icon_list_control_finalize (GObject* obj);
static void icon_list_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void icon_list_control_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static int _vala_strcmp0 (const char * str1, const char * str2);



IconListControl* icon_list_control_construct (GType object_type, GtkListStore* model, GError** error) {
	GError * _inner_error_;
	IconListControl * self;
	g_return_val_if_fail (model != NULL, NULL);
	_inner_error_ = NULL;
	self = (IconListControl*) g_object_new (object_type, NULL);
	icon_list_control_set_iconlist_store (self, model);
	if (!icon_list_control_pixbufs_loaded) {
		icon_list_control_setup_icons (self, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		}
		icon_list_control_pixbufs_loaded = TRUE;
	}
	icon_list_control_setup_elements (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return NULL;
	}
	return self;
}


IconListControl* icon_list_control_new (GtkListStore* model, GError** error) {
	return icon_list_control_construct (TYPE_ICON_LIST_CONTROL, model, error);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gpointer _gst_object_ref0 (gpointer self) {
	return self ? gst_object_ref (self) : NULL;
}


static void _icon_list_control_on_bus_message_gst_bus_message (GstBus* _sender, GstMessage* message, gpointer self) {
	icon_list_control_on_bus_message (self, message);
}


void icon_list_control_setup_icons (IconListControl* self, GError** error) {
	GError * _inner_error_;
	GtkIconTheme* icon_theme;
	GtkIconInfo* icon_info;
	GtkIconInfo* _tmp0_;
	GtkIconInfo* _tmp3_;
	GstElement* _tmp6_;
	GstPipeline* _tmp8_;
	GstElement* _tmp7_;
	GstElement* _tmp9_;
	GstElement* _tmp10_;
	GstBus* bus;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	icon_theme = _g_object_ref0 (gtk_icon_theme_get_default ());
	icon_info = NULL;
	icon_info = (_tmp0_ = gtk_icon_theme_lookup_icon (icon_theme, GTK_STOCK_MISSING_IMAGE, 128, GTK_ICON_LOOKUP_FORCE_SIZE), _gtk_icon_info_free0 (icon_info), _tmp0_);
	if (icon_info != NULL) {
		GdkPixbuf* _tmp1_;
		GdkPixbuf* _tmp2_;
		_tmp1_ = gtk_icon_info_load_icon (icon_info, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (icon_theme);
			_gtk_icon_info_free0 (icon_info);
			return;
		}
		self->missing_pixbuf = (_tmp2_ = _tmp1_, _g_object_unref0 (self->missing_pixbuf), _tmp2_);
	}
	icon_info = (_tmp3_ = gtk_icon_theme_lookup_icon (icon_theme, "image-loading", 128, GTK_ICON_LOOKUP_FORCE_SIZE), _gtk_icon_info_free0 (icon_info), _tmp3_);
	if (icon_info != NULL) {
		GdkPixbuf* _tmp4_;
		GdkPixbuf* _tmp5_;
		_tmp4_ = gtk_icon_info_load_icon (icon_info, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (icon_theme);
			_gtk_icon_info_free0 (icon_info);
			return;
		}
		icon_list_control_loading_pixbuf = (_tmp5_ = _tmp4_, _g_object_unref0 (icon_list_control_loading_pixbuf), _tmp5_);
	}
	_tmp6_ = gst_parse_launch (PIXBUF_PIPELINE_DESC, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (icon_theme);
		_gtk_icon_info_free0 (icon_info);
		return;
	}
	self->pipeline = (_tmp8_ = (_tmp7_ = _tmp6_, GST_IS_PIPELINE (_tmp7_) ? ((GstPipeline*) _tmp7_) : NULL), _gst_object_unref0 (self->pipeline), _tmp8_);
	if ((self->filesrc = (_tmp9_ = gst_bin_get_by_name ((GstBin*) self->pipeline, "filesrc"), _gst_object_unref0 (self->filesrc), _tmp9_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named filesrc in the pixbuf pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (icon_theme);
			_gtk_icon_info_free0 (icon_info);
			return;
		}
	}
	if ((self->imagesink = (_tmp10_ = gst_bin_get_by_name ((GstBin*) self->pipeline, "imagesink"), _gst_object_unref0 (self->imagesink), _tmp10_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named imagesink in the pixbuf pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (icon_theme);
			_gtk_icon_info_free0 (icon_info);
			return;
		}
	}
	bus = _gst_object_ref0 (((GstElement*) self->pipeline)->bus);
	gst_bus_add_signal_watch (bus);
	g_signal_connect_object (bus, "message", (GCallback) _icon_list_control_on_bus_message_gst_bus_message, self, 0);
	_g_object_unref0 (icon_theme);
	_gtk_icon_info_free0 (icon_info);
	_gst_object_unref0 (bus);
}


void icon_list_control_setup_elements (IconListControl* self, GError** error) {
	GError * _inner_error_;
	GstElement* _tmp0_;
	GstPipeline* _tmp2_;
	GstElement* _tmp1_;
	GstElement* _tmp3_;
	GstElement* _tmp4_;
	GstBus* bus;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	_tmp0_ = gst_parse_launch (PIXBUF_PIPELINE_DESC, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->pipeline = (_tmp2_ = (_tmp1_ = _tmp0_, GST_IS_PIPELINE (_tmp1_) ? ((GstPipeline*) _tmp1_) : NULL), _gst_object_unref0 (self->pipeline), _tmp2_);
	if ((self->filesrc = (_tmp3_ = gst_bin_get_by_name ((GstBin*) self->pipeline, "filesrc"), _gst_object_unref0 (self->filesrc), _tmp3_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named filesrc in the pixbuf pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
	if ((self->imagesink = (_tmp4_ = gst_bin_get_by_name ((GstBin*) self->pipeline, "imagesink"), _gst_object_unref0 (self->imagesink), _tmp4_)) == NULL) {
		_inner_error_ = g_error_new_literal (GST_CORE_ERROR, GST_CORE_ERROR_FAILED, "No element named imagesink in the pixbuf pipeline");
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
	bus = _gst_object_ref0 (((GstElement*) self->pipeline)->bus);
	gst_bus_add_signal_watch (bus);
	g_signal_connect_object (bus, "message", (GCallback) _icon_list_control_on_bus_message_gst_bus_message, self, 0);
	_gst_object_unref0 (bus);
}


static void icon_list_control_add_folder_data_free (gpointer _data) {
	IconListControlAddFolderData* data;
	data = _data;
	_g_free0 (data->dirname);
	g_slice_free (IconListControlAddFolderData, data);
}


void icon_list_control_add_folder (IconListControl* self, const char* dirname, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	IconListControlAddFolderData* _data_;
	_data_ = g_slice_new0 (IconListControlAddFolderData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, icon_list_control_add_folder);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, icon_list_control_add_folder_data_free);
	_data_->self = self;
	_data_->dirname = g_strdup (dirname);
	icon_list_control_add_folder_co (_data_);
}


void icon_list_control_add_folder_finish (IconListControl* self, GAsyncResult* _res_) {
	IconListControlAddFolderData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void icon_list_control_add_folder_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	IconListControlAddFolderData* data;
	data = _user_data_;
	data->_res_ = _res_;
	icon_list_control_add_folder_co (data);
}


static void _g_list_free_g_object_unref (GList* self) {
	g_list_foreach (self, (GFunc) g_object_unref, NULL);
	g_list_free (self);
}


static gboolean icon_list_control_add_folder_co (IconListControlAddFolderData* data) {
	switch (data->_state_) {
		default:
		g_assert_not_reached ();
		case 0:
		{
			data->dir = g_file_new_for_path (data->dirname);
			{
				g_file_enumerate_children_async (data->dir, IMAGE_FILE_ATTRIBUTES, G_FILE_QUERY_INFO_NONE, G_PRIORITY_DEFAULT, NULL, icon_list_control_add_folder_ready, data);
				data->_state_ = 1;
				return FALSE;
				case 1:
				data->file_etor = g_file_enumerate_children_finish (data->dir, data->_res_, &data->_inner_error_);
				if (data->_inner_error_ != NULL) {
					goto __catch1_g_error;
					goto __finally1;
				}
				while (TRUE) {
					g_file_enumerator_next_files_async (data->file_etor, 5, G_PRIORITY_DEFAULT, NULL, icon_list_control_add_folder_ready, data);
					data->_state_ = 2;
					return FALSE;
					case 2:
					data->files = g_file_enumerator_next_files_finish (data->file_etor, data->_res_, &data->_inner_error_);
					if (data->_inner_error_ != NULL) {
						_g_object_unref0 (data->file_etor);
						goto __catch1_g_error;
						goto __finally1;
					}
					if (data->files == NULL) {
						__g_list_free_g_object_unref0 (data->files);
						break;
					}
					icon_list_control_add_next_files (data->self, data->dirname, data->files);
					__g_list_free_g_object_unref0 (data->files);
				}
				icon_list_control_retrieve_icons (data->self, icon_list_control_add_folder_ready, data);
				data->_state_ = 3;
				return FALSE;
				case 3:
				icon_list_control_retrieve_icons_finish (data->self, data->_res_);
				_g_object_unref0 (data->file_etor);
			}
			goto __finally1;
			__catch1_g_error:
			{
				data->e1 = data->_inner_error_;
				data->_inner_error_ = NULL;
				{
					g_print ("%s", data->_tmp0_ = g_strconcat (data->e1->message, "\n", NULL));
					_g_free0 (data->_tmp0_);
					_g_error_free0 (data->e1);
				}
			}
			__finally1:
			if (data->_inner_error_ != NULL) {
				_g_object_unref0 (data->dir);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, data->_inner_error_->message, g_quark_to_string (data->_inner_error_->domain), data->_inner_error_->code);
				g_clear_error (&data->_inner_error_);
				return FALSE;
			}
			_g_object_unref0 (data->dir);
		}
		{
			if (data->_state_ == 0) {
				g_simple_async_result_complete_in_idle (data->_async_result);
			} else {
				g_simple_async_result_complete (data->_async_result);
			}
			g_object_unref (data->_async_result);
			return FALSE;
		}
	}
}


void icon_list_control_add_next_files (IconListControl* self, const char* dirname, GList* files) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (dirname != NULL);
	{
		GList* info_collection;
		GList* info_it;
		info_collection = files;
		for (info_it = info_collection; info_it != NULL; info_it = info_it->next) {
			GFileInfo* info;
			info = _g_object_ref0 ((GFileInfo*) info_it->data);
			{
				if (_vala_strcmp0 (g_file_info_get_content_type (info), "image/jpeg") == 0) {
					char* file;
					char* text;
					file = g_build_filename (dirname, g_file_info_get_name (info), NULL);
					text = g_strdup (g_file_info_get_display_name (info));
					gtk_list_store_insert_with_values (self->priv->_iconlist_store, NULL, -1, IMAGE_LIST_COL_TEXT, text, IMAGE_LIST_COL_FILE, file, IMAGE_LIST_COL_PIXBUF, icon_list_control_loading_pixbuf, -1, -1);
					_g_free0 (file);
					_g_free0 (text);
				}
				_g_object_unref0 (info);
			}
		}
	}
}


static void icon_list_control_retrieve_icons_data_free (gpointer _data) {
	IconListControlRetrieveIconsData* data;
	data = _data;
	g_slice_free (IconListControlRetrieveIconsData, data);
}


void icon_list_control_retrieve_icons (IconListControl* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	IconListControlRetrieveIconsData* _data_;
	_data_ = g_slice_new0 (IconListControlRetrieveIconsData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, icon_list_control_retrieve_icons);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, icon_list_control_retrieve_icons_data_free);
	_data_->self = self;
	icon_list_control_retrieve_icons_co (_data_);
}


void icon_list_control_retrieve_icons_finish (IconListControl* self, GAsyncResult* _res_) {
	IconListControlRetrieveIconsData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void icon_list_control_retrieve_icons_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	IconListControlRetrieveIconsData* data;
	data = _user_data_;
	data->_res_ = _res_;
	icon_list_control_retrieve_icons_co (data);
}


static gboolean _icon_list_control_retrieve_icons_co_gsource_func (gpointer self) {
	return icon_list_control_retrieve_icons_co (self);
}


static inline void _dynamic_set_location0 (GstElement* obj, const char* value) {
	g_object_set (obj, "location", value, NULL);
}


static gboolean icon_list_control_retrieve_icons_co (IconListControlRetrieveIconsData* data) {
	switch (data->_state_) {
		default:
		g_assert_not_reached ();
		case 0:
		{
			if (gtk_tree_model_get_iter_first ((GtkTreeModel*) data->self->priv->_iconlist_store, &data->iter)) {
				data->self->continuation = (data->_tmp0_ = _icon_list_control_retrieve_icons_co_gsource_func, ((data->self->continuation_target_destroy_notify == NULL) ? NULL : data->self->continuation_target_destroy_notify (data->self->continuation_target), data->self->continuation = NULL, data->self->continuation_target = NULL, data->self->continuation_target_destroy_notify = NULL), data->self->continuation_target = data, data->self->continuation_target_destroy_notify = NULL, data->_tmp0_);
				{
					data->_tmp1_ = TRUE;
					while (TRUE) {
						if (!data->_tmp1_) {
							if (!gtk_tree_model_iter_next ((GtkTreeModel*) data->self->priv->_iconlist_store, &data->iter)) {
								break;
							}
						}
						data->_tmp1_ = FALSE;
						gtk_tree_model_get ((GtkTreeModel*) data->self->priv->_iconlist_store, &data->iter, IMAGE_LIST_COL_TEXT, &data->display, IMAGE_LIST_COL_FILE, &data->file, -1, -1);
						icon_list_control_last_pixbuf = (data->_tmp2_ = NULL, _g_object_unref0 (icon_list_control_last_pixbuf), data->_tmp2_);
						data->self->continuation_error = (data->_tmp3_ = NULL, _g_error_free0 (data->self->continuation_error), data->_tmp3_);
						_dynamic_set_location0 (data->self->filesrc, data->file);
						gst_element_set_state ((GstElement*) data->self->pipeline, GST_STATE_PLAYING);
						data->_state_ = 4;
						return FALSE;
						case 4:
						;
						if (data->self->continuation_error == NULL) {
							data->_tmp4_ = icon_list_control_last_pixbuf != NULL;
						} else {
							data->_tmp4_ = FALSE;
						}
						if (data->_tmp4_) {
							data->pixbuf = (data->_tmp5_ = _g_object_ref0 (icon_list_control_last_pixbuf), _g_object_unref0 (data->pixbuf), data->_tmp5_);
						} else {
							data->pixbuf = (data->_tmp6_ = _g_object_ref0 (data->self->missing_pixbuf), _g_object_unref0 (data->pixbuf), data->_tmp6_);
						}
						gtk_list_store_set (data->self->priv->_iconlist_store, &data->iter, IMAGE_LIST_COL_PIXBUF, data->pixbuf, -1, -1);
						gst_element_set_state ((GstElement*) data->self->pipeline, GST_STATE_READY);
						_g_free0 (data->file);
						_g_free0 (data->display);
						_g_object_unref0 (data->pixbuf);
					}
				}
			}
		}
		{
			if (data->_state_ == 0) {
				g_simple_async_result_complete_in_idle (data->_async_result);
			} else {
				g_simple_async_result_complete (data->_async_result);
			}
			g_object_unref (data->_async_result);
			return FALSE;
		}
	}
}


static gpointer _gst_structure_copy0 (gpointer self) {
	return self ? gst_structure_copy (self) : NULL;
}


static inline GdkPixbuf* _dynamic_get_last_pixbuf1 (GstElement* obj) {
	GdkPixbuf* result;
	g_object_get (obj, "last-pixbuf", &result, NULL);
	return result;
}


void icon_list_control_on_bus_message (IconListControl* self, GstMessage* message) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	switch (message->type) {
		case GST_MESSAGE_ERROR:
		{
			{
				GError* _tmp1_;
				GError* _tmp0_ = NULL;
				gst_message_parse_error (message, &_tmp0_, NULL);
				self->continuation_error = (_tmp1_ = _tmp0_, _g_error_free0 (self->continuation_error), _tmp1_);
				g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, self->continuation, self->continuation_target, NULL);
			}
			break;
		}
		case GST_MESSAGE_ELEMENT:
		{
			{
				if (message->src == GST_OBJECT (self->imagesink)) {
					GstStructure* structure;
					GstStructure* _tmp2_;
					structure = NULL;
					if ((structure = (_tmp2_ = _gst_structure_copy0 (message->structure), _gst_structure_free0 (structure), _tmp2_)) != NULL) {
						if (structure->name == icon_list_control_pixbuf_q) {
							GdkPixbuf* _tmp3_;
							icon_list_control_last_pixbuf = (_tmp3_ = _dynamic_get_last_pixbuf1 (self->imagesink), _g_object_unref0 (icon_list_control_last_pixbuf), _tmp3_);
						}
					}
					_gst_structure_free0 (structure);
				}
			}
			break;
		}
		case GST_MESSAGE_EOS:
		{
			{
				g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, self->continuation, self->continuation_target, NULL);
			}
			break;
		}
		default:
		{
			{
				;
			}
			break;
		}
	}
}


GtkListStore* icon_list_control_get_iconlist_store (IconListControl* self) {
	GtkListStore* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_iconlist_store;
	return result;
}


void icon_list_control_set_iconlist_store (IconListControl* self, GtkListStore* value) {
	g_return_if_fail (self != NULL);
	self->priv->_iconlist_store = value;
	g_object_notify ((GObject *) self, "iconlist-store");
}


static void icon_list_control_class_init (IconListControlClass * klass) {
	icon_list_control_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (IconListControlPrivate));
	G_OBJECT_CLASS (klass)->get_property = icon_list_control_get_property;
	G_OBJECT_CLASS (klass)->set_property = icon_list_control_set_property;
	G_OBJECT_CLASS (klass)->finalize = icon_list_control_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ICON_LIST_CONTROL_ICONLIST_STORE, g_param_spec_object ("iconlist-store", "iconlist-store", "iconlist-store", GTK_TYPE_LIST_STORE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	icon_list_control_pixbuf_q = g_quark_from_string ("pixbuf");
}


static void icon_list_control_instance_init (IconListControl * self) {
	self->priv = ICON_LIST_CONTROL_GET_PRIVATE (self);
}


static void icon_list_control_finalize (GObject* obj) {
	IconListControl * self;
	self = ICON_LIST_CONTROL (obj);
	{
		if (self->pipeline != NULL) {
			gst_element_set_state ((GstElement*) self->pipeline, GST_STATE_NULL);
		}
	}
	_gst_object_unref0 (self->pipeline);
	_gst_object_unref0 (self->filesrc);
	_gst_object_unref0 (self->imagesink);
	_g_object_unref0 (self->missing_pixbuf);
	(self->continuation_target_destroy_notify == NULL) ? NULL : self->continuation_target_destroy_notify (self->continuation_target);
	self->continuation = NULL;
	self->continuation_target = NULL;
	self->continuation_target_destroy_notify = NULL;
	_g_error_free0 (self->continuation_error);
	G_OBJECT_CLASS (icon_list_control_parent_class)->finalize (obj);
}


GType icon_list_control_get_type (void) {
	static GType icon_list_control_type_id = 0;
	if (icon_list_control_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (IconListControlClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) icon_list_control_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IconListControl), 0, (GInstanceInitFunc) icon_list_control_instance_init, NULL };
		icon_list_control_type_id = g_type_register_static (G_TYPE_OBJECT, "IconListControl", &g_define_type_info, 0);
	}
	return icon_list_control_type_id;
}


static void icon_list_control_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	IconListControl * self;
	self = ICON_LIST_CONTROL (object);
	switch (property_id) {
		case ICON_LIST_CONTROL_ICONLIST_STORE:
		g_value_set_object (value, icon_list_control_get_iconlist_store (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void icon_list_control_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	IconListControl * self;
	self = ICON_LIST_CONTROL (object);
	switch (property_id) {
		case ICON_LIST_CONTROL_ICONLIST_STORE:
		icon_list_control_set_iconlist_store (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




