/* imageview-app.c generated by valac, the Vala compiler
 * generated from imageview-app.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gst/gst.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_IMAGE_VIEW_WINDOW (image_view_window_get_type ())
#define IMAGE_VIEW_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IMAGE_VIEW_WINDOW, ImageViewWindow))
#define IMAGE_VIEW_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IMAGE_VIEW_WINDOW, ImageViewWindowClass))
#define IS_IMAGE_VIEW_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IMAGE_VIEW_WINDOW))
#define IS_IMAGE_VIEW_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IMAGE_VIEW_WINDOW))
#define IMAGE_VIEW_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IMAGE_VIEW_WINDOW, ImageViewWindowClass))

typedef struct _ImageViewWindow ImageViewWindow;
typedef struct _ImageViewWindowClass ImageViewWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



#define style "\nstyle \"custom\"\n{\n    GtkComboBox::appears-as-list = 1\n}\n\nwidget_class \"*ComboBox*\" style \"custom\"\n"
ImageViewWindow* image_view_window_new (void);
ImageViewWindow* image_view_window_construct (GType object_type);
GType image_view_window_get_type (void);
void _main (char** args, int args_length1);



void _main (char** args, int args_length1) {
	ImageViewWindow* window;
	gtk_init (&args_length1, &args);
	gst_init (&args_length1, &args);
	gtk_rc_parse_string (style);
	window = g_object_ref_sink (image_view_window_new ());
	gtk_widget_show ((GtkWidget*) window);
	gtk_main ();
	_g_object_unref0 (window);
}


int main (int argc, char ** argv) {
	g_type_init ();
	_main (argv, argc);
	return 0;
}




