/* imageview-app.c generated by valac, the Vala compiler
 * generated from imageview-app.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gst/gst.h>
#include <gtk/gtk.h>
#include <common.h>
#include <stdlib.h>
#include <string.h>


#define OMAP_TYPE_IMAGE_VIEW_WINDOW (omap_image_view_window_get_type ())
#define OMAP_IMAGE_VIEW_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMAP_TYPE_IMAGE_VIEW_WINDOW, OmapImageViewWindow))
#define OMAP_IMAGE_VIEW_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMAP_TYPE_IMAGE_VIEW_WINDOW, OmapImageViewWindowClass))
#define OMAP_IS_IMAGE_VIEW_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMAP_TYPE_IMAGE_VIEW_WINDOW))
#define OMAP_IS_IMAGE_VIEW_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMAP_TYPE_IMAGE_VIEW_WINDOW))
#define OMAP_IMAGE_VIEW_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMAP_TYPE_IMAGE_VIEW_WINDOW, OmapImageViewWindowClass))

typedef struct _OmapImageViewWindow OmapImageViewWindow;
typedef struct _OmapImageViewWindowClass OmapImageViewWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



OmapImageViewWindow* omap_image_view_window_new (GError** error);
OmapImageViewWindow* omap_image_view_window_construct (GType object_type, GError** error);
GType omap_image_view_window_get_type (void);
void _main (char** args, int args_length1);



void _main (char** args, int args_length1) {
	GError * _inner_error_;
	_inner_error_ = NULL;
	gst_init (&args_length1, &args);
	gtk_init (&args_length1, &args);
	{
		OmapImageViewWindow* window;
		window = g_object_ref_sink (omap_image_view_window_new (&_inner_error_));
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
			goto __finally0;
		}
		gtk_widget_show ((GtkWidget*) window);
		gtk_main ();
		_g_object_unref0 (window);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			omap_error_dialog (e);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


int main (int argc, char ** argv) {
	g_type_init ();
	_main (argv, argc);
	return 0;
}




